<div class="product-widget__inner br whitesmoke" style="margin-top:30px;">
    <div class="heading-sec clearfix">
        <h2 class="pull-left">People who bought this item also bought</h2>
    </div>
    <div class="block widget block-products-list grid">
        <div class="block-content">
            <!-- new_products_content_widget_grid-->
            <div class="products-grid grid">
                <ol class="product-items widget-product-grid list-unstyled clearfix">
                    <li class="item product product-item col-xs-6 col-sm-4 col-md-3 col-lg-20">
                        <div class="product-item-info">
                            <a href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html" class="product-item-photo">

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="http://shopcsntv.com/media/catalog/product/cache/1/small_image/200x/05e17a266b0e9cc26fb81a2e0bed7e78/0/3/034386_2018_noahs_ark_bu.jpg"
                                            alt="LifeLong Fitness IV"></span>
                                </span>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="LifeLong Fitness IV" href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html"
                                        class="product-item-link">
                                        LifeLong Fitness IV</a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="46">


                                    <span class="price-container price-final_price tax weee">
                                        <span id="old-price-46-widget-product-grid" data-price-amount="14"
                                            data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">$14.00</span> </span>
                                    </span>

                                </div>

                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <button class="action qview primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Quick View">
                                            <span>Quick View</span>
                                        </button>
                                        <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Add to Cart">
                                            <span>Add to Cart</span>
                                        </button>
                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                            <span class="fa fa-heart-o"></span>
                                        </a>
                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            title="Add to Compare">
                                            <span>Add to Compare</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="item product product-item col-xs-6 col-sm-4 col-md-3 col-lg-20">
                        <div class="product-item-info">
                            <a href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html" class="product-item-photo">

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="http://shopcsntv.com/media/catalog/product/cache/1/small_image/200x/05e17a266b0e9cc26fb81a2e0bed7e78/0/3/034386_2018_noahs_ark_bu.jpg"
                                            alt="LifeLong Fitness IV"></span>
                                </span>
                                <span class="sale-promo"></span>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="LifeLong Fitness IV" href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html"
                                        class="product-item-link">
                                        LifeLong Fitness IV </a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="46">


                                    <span class="price-container price-final_price tax weee">
                                        <span id="old-price-46-widget-product-grid" data-price-amount="14"
                                            data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">$14.00</span> </span>
                                    </span>

                                </div>

                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <button class="action qview primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Quick View">
                                            <span>Quick View</span>
                                        </button>
                                        <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Add to Cart">
                                            <span>Add to Cart</span>
                                        </button>
                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                            <span class="fa fa-heart-o"></span>
                                        </a>
                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            title="Add to Compare">
                                            <span>Add to Compare</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="item product product-item col-xs-6 col-sm-4 col-md-3 col-lg-20">
                        <div class="product-item-info">
                            <a href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html" class="product-item-photo">

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="http://shopcsntv.com/media/catalog/product/cache/1/small_image/200x/05e17a266b0e9cc26fb81a2e0bed7e78/0/3/034386_2018_noahs_ark_bu.jpg"
                                            alt="LifeLong Fitness IV"></span>
                                </span>
<!--                                <span class="sale-promo"><img src="images/tag_sale.png"></span>-->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="LifeLong Fitness IV" href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html"
                                        class="product-item-link">
                                        LifeLong Fitness IV </a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="46">


                                    <span class="price-container price-final_price tax weee">
                                        <span id="old-price-46-widget-product-grid" data-price-amount="14"
                                            data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">$14.00</span> </span>
                                    </span>

                                </div>

                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <button class="action qview primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Quick View">
                                            <span>Quick View</span>
                                        </button>
                                        <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Add to Cart">
                                            <span>Add to Cart</span>
                                        </button>
                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                            <span class="fa fa-heart-o"></span>
                                        </a>
                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            title="Add to Compare">
                                            <span>Add to Compare</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="item product product-item col-xs-6 col-sm-4 col-md-3 col-lg-20">
                        <div class="product-item-info">
                            <a href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html" class="product-item-photo">

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="http://shopcsntv.com/media/catalog/product/cache/1/small_image/200x/05e17a266b0e9cc26fb81a2e0bed7e78/0/3/034386_2018_noahs_ark_bu.jpg"
                                            alt="LifeLong Fitness IV"></span>
                                </span>
<!--                                <span class="sale-promo"><img src="images/tag_sale.png"></span>-->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="LifeLong Fitness IV" href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html"
                                        class="product-item-link">
                                        LifeLong Fitness IV </a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="46">


                                    <span class="price-container price-final_price tax weee">
                                        <span id="old-price-46-widget-product-grid" data-price-amount="14"
                                            data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">$14.00</span> </span>
                                    </span>

                                </div>

                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <button class="action qview primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Quick View">
                                            <span>Quick View</span>
                                        </button>
                                        <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Add to Cart">
                                            <span>Add to Cart</span>
                                        </button>
                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                            <span class="fa fa-heart-o"></span>
                                        </a>
                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            title="Add to Compare">
                                            <span>Add to Compare</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="item product product-item col-xs-6 col-sm-4 col-md-3 col-lg-20">
                        <div class="product-item-info">
                            <a href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html" class="product-item-photo">

                                <span class="product-image-container">
                                    <span class="product-image-wrapper">
                                        <img class="product-image-photo" src="http://shopcsntv.com/media/catalog/product/cache/1/small_image/200x/05e17a266b0e9cc26fb81a2e0bed7e78/0/3/034386_2018_noahs_ark_bu.jpg"
                                            alt="LifeLong Fitness IV"></span>
                                </span>
                                <span class="sale-promo"><img src="images/tag_sale.png"></span>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="LifeLong Fitness IV" href="http://magento2-demo.nexcess.net/lifelong-fitness-iv.html"
                                        class="product-item-link">
                                        LifeLong Fitness IV </a>
                                </strong>
                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="46">


                                    <span class="price-container price-final_price tax weee">
                                        <span id="old-price-46-widget-product-grid" data-price-amount="14"
                                            data-price-type="finalPrice" class="price-wrapper ">
                                            <span class="price">$14.00</span> </span>
                                    </span>

                                </div>

                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Add to Cart">
                                            <span>Add to Cart</span>
                                        </button>
                                        <button class="action qview primary" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/checkout\/cart\/add\/uenc\/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv\/product\/46\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            type="button" title="Quick View">
                                            <span>Quick View</span>
                                        </button>

                                    </div>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                            <span class="fa fa-heart-o"></span>
                                        </a>
                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/magento2-demo.nexcess.net\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;46&quot;,&quot;uenc&quot;:&quot;aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQv&quot;}}"
                                            title="Add to Compare">
                                            <span>Add to Compare</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>

                </ol>
            </div>
        </div>
    </div>
</div>