<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php
$_product = $block->getProduct();
$viewModel = $block->getData('productViewModel');
$attributeText = $_product->getAttributeText('grouped_product_type');
$attributeCode = strtolower($attributeText);
?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= $attributeText ? $attributeText : __('Product Name') ?></th>
            <?php if ($block->getCanShowProductPrice($_product)): ?>
                <th class="col price" scope="col"><?= /* @escapeNotVerified */ __('CasePrice') ?></th>
            <?php endif; ?>

            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
        <tbody>
        <?php foreach ($_associatedProducts as $_item): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                    <img src="<?= $viewModel->getImageUrl($_item) ?>" />
                    <strong class="product-item-name"><?= $block->escapeHtml($attributeText ? $viewModel->getCustomAttribute($_item->getSku(), $attributeCode) ?? $_item->getName() : $_item->getName()) ?></strong>
                </td>
                
                <?php if ($block->getCanShowProductPrice($_product)): ?>
                    <td data-th="<?= $block->escapeHtml(__('CasePrice')) ?>" class="col price">
                        <?php $casePrice = $viewModel->getCasePrice($_item); ?>
                        <?php if ($block->getCanShowProductPrice($_item) && !$viewModel->getCustomerId()): ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                        <?php else: ?>
                            <?= $casePrice ?>
                        <?php endif; ?>
                    </td>
                <?php endif; ?>

                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
                <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty">
                        <button type="button" class="decreaseQty"><span>-</span></button>
                        <input type="number"
                               name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                               value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"
                               data-advanced-inventory = "<?= $block->escapeHtml($viewModel->getQuantityValidators($_item->getId(), $_item->getStore()->getWebsiteId())) ?>"
                               />
                        <button type="button" class="increaseQty"><span>+</span></button>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                        <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Theme/js/action": {}
        }
    }
</script>
