<?php
use Magento\Store\Model\ScopeInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$scopeConfig = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');

$storeName = $scopeConfig->getValue('general/store_information/name',ScopeInterface::SCOPE_STORE);
$phoneNo = $scopeConfig->getValue('general/store_information/phone',ScopeInterface::SCOPE_STORE);
$storeAddress1 = $scopeConfig->getValue('general/store_information/street_line1',ScopeInterface::SCOPE_STORE);
$storeAddress2 = $scopeConfig->getValue('general/store_information/street_line2',ScopeInterface::SCOPE_STORE);
$storeCity = $scopeConfig->getValue('general/store_information/city',ScopeInterface::SCOPE_STORE);
$storeZip = $scopeConfig->getValue('general/store_information/postcode',ScopeInterface::SCOPE_STORE);
?>

<div id="map" style="display: none;">
    <?php echo $storeAddress1;?><br>
    <?php echo $storeAddress2;?>, <?php echo $storeCity; ?><br>
    <?php echo $storeZip?>
</div>

<div style="width: 100%"><iframe width="100%" height="600" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d32713.63040635899!2d-96.64368831572304!3d33.143070161590046!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x864c11091926bd13%3A0xce43380e4c82f154!2sFairview%2C+TX+75069%2C+USA!5e0!3m2!1sen!2sin!4v1559568151982!5m2!1sen!2sin" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe></div>