<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-bottom-container">
    <div class="d-flex justify-content-between align-items-center row">
        <div class="link-copyright col-12 col-md-6">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-bottom')->toHtml(); ?>
            <small class="copyright">
                <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
            </small>
        </div>
        <div class="payment-wrap col-12 col-md-6">
            <div class="payment-icons">
                <img src="<?php echo $block->getViewFileUrl('images/payment_card.png');?>" alt="">
            </div>
        </div>
    </div>
</div>

<script>
    require([
            'jquery',
            'jquery/ui',
            'slick',
            'bootstrap',
            'wow',
            'scroller',
            'custom'],
        function ($) {

        });
</script>
