<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="footer-top-container">
    <div class="inner-sec d-flex justify-content-between align-items-center row">
    <div class="footer-logo col-12 col-md-6 hidden-md">
        <img src="<?= $block->getLayout()->getBlock('logo')->getLogoSrc() ?>" alt="Gogoballonz"/>

    </div>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-top')->toHtml(); ?>
    </div>
</div>
