<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="footer-top-container">
    <div class="inner-sec d-flex justify-content-between align-items-center">
    <div class="footer-logo col col-sm-6">
        <img src="<?= $block->getLayout()->getBlock('logo')->getLogoSrc() ?>" alt="Gogoballonz"/>

    </div>
        <div class="contact-info col col-sm-6">
            <a href="tel:469-555-1212" class="icon-ph">(469)-555-1212</a>
            <a href="mailto:hi@gogoballonz.com" class="icon-email">hi@gogoballonz.com</a>
        </div>
    </div>
</div>
