<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_links_images')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('featured-product-section')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotional_banner')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_seller')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('delivery_banner')->toHtml(); ?>