<section class="sec-space">
    <div class="home-slider full-img">
        <div class="banner-item" >
            <div class="slide-content">
                <h2 class="display-5 mb-2" data-animation="slideInLeft"><span class="text-primary">Limits</span></h2>
                <p class="text-uppercase"><a href="#" class="pre-line">Learn more</a></p>
            </div>
            <img src="<?php echo $block->getViewFileUrl('images/01_banner.jpg'); ?>" alt=""  />
        </div>
    </div>
</section>