<section class="sec-space">
    <div class="home-slider full-img">
        <div class="banner-item" >
            <div class="slide-content">
                <div class="slide-content-inner">
                    <h2 class="display-5 mb-2" data-animation="slideInLeft">Shop Party Balloons <span>for every occasion!</span></h2>
                    <a href="#" class="btn btn-outline-blue" data-animation="slideInDown">Shop Now</a>
                </div>
            </div>
            <img src="<?php echo $block->getViewFileUrl('images/01_banner.jpg'); ?>" alt=""  />
        </div>
        <div class="banner-item" >
            <div class="slide-content">
                <div class="slide-content-inner">
                    <h2 class="display-5 mb-2" data-animation="slideInUp">Shop Party Balloons <span>for every occasion!</span></h2>
                    <a href="#" class="btn btn-outline-blue" data-animation="slideInDown">Shop Now</a>
                </div>
            </div>
            <img src="<?php echo $block->getViewFileUrl('images/02_banner.jpg'); ?>" alt=""  />
        </div>
        <div class="banner-item" >
            <div class="slide-content">
                <div class="slide-content-inner">
                    <h2 class="display-5 mb-2" data-animation="slideInDown">Shop Party Balloons <span>for every occasion!</span></h2>
                    <a href="#" class="btn btn-outline-blue" data-animation="slideInDown">Shop Now</a>
                </div>
            </div>
            <img src="<?php echo $block->getViewFileUrl('images/03_banner.jpg'); ?>" alt=""  />
        </div>
    </div>
    <a class="scroll-down" href="#category-sec">↓</a>
</section>