
<div class="pre-loader">
    <div class="loader-img">
        <img src="<?php echo $block->getViewFileUrl('images/loader.svg')?>">
    </div>
</div>

<script>
    require(['jquery'], function($){
        $(window).load(function() {
            $(".pre-loader").fadeOut("slow");
        });
    });
</script>
<style>
    .pre-loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        background: rgba(255,255,255,0.98);
        display: table;
        text-align: center;
    }

    .loader-img {
        display: table-cell;
        vertical-align: middle;
    }
</style>