<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getOrder() ?>

<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildrenItems()); ?>

<?php if ($block->getItemOptions() || $_item->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>

            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getParentItem()): ?>
        <tr class="bundle-item bundle-parent">
            <td class="item-info" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px; border-top: 1px solid #d8dde7;">
                <p class="product-name" style="margin-top: 0; font-weight: 700; margin-bottom: 5px; color: #001842;"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku" style="margin-top: 0; margin-bottom: 10px;"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
            <td class="item-qty" style="font-weight: 600; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px; border-top: 1px solid #d8dde7; text-align: center;">
                <?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?>
            </td>
            <td class="item-price" style="color: #ff1200; font-weight: 600; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px; border-top: 1px solid #d8dde7; text-align: right;">
                <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
            </td>
        </tr>
    <?php else: ?>

    <?php endif; ?>

<?php endforeach; ?>

<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                            <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
                <table class="message-gift">
                    <tr>
                        <td>
                            <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                            <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                            <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>

