<?php $catalogPage = $block->getViewModel()->getCatalogPage() ?>
<?php if ($catalogPage): ?>
<a class="master-catalog-link" rel=”nofollow” title="<?= __('View Page %1', $catalogPage['catalog_page_number']); ?>" href="<?php echo $catalogPage['catalog_link'] ?>">
    <div class="master-catalog-listing">
        <h2 class="header"><?= __('Master Catalog Listing'); ?></h2>
        <p><?= __('View Page %1', $catalogPage['catalog_page_number']); ?></p>
    </div>
</a>
<?php endif; ?>
