<?php if ($block->getBanners()) : ?>
    <div class="home-banner">
        <?php foreach ($block->getBanners() as $banner) { ?>
        <div><a href="<?php echo $banner->getLink(); ?>"><img src="<?php echo $banner->getImageUrl(); ?>" alt="" /></a></div>
        <?php } ?>
    </div>
<?php endif; ?>
<script>
requirejs(['jquery','Ziffity_Banners/js/slick.min'], function($){
        $('.home-banner').slick({
        autoplay:true,
        autoplaySpeed:3000,
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear'
    });
})
</script>