<?php if ($block->getBanners()) : ?>
<section class="sec-space home-banner ">
    <div class="home-slider full-img">
        <?php foreach ($block->getBanners() as $banner) { ?>
        <div class="banner-item" >
            <div class="slide-content">
                <div class="slide-content-inner">
                    <h2 class="display-5 mb-2">Shop Party Balloons <span>for every occasion!</span></h2>
                    <a href="<?php echo $banner->getLink(); ?>" class="btn btn-outline-blue">Shop Now</a>
                </div>
            </div>
            <img src="<?php echo $banner->getImageUrl(); ?>" alt=""  />
        </div>
        <?php } ?>
    </div>
    <a class="scroll-down" href="#category-sec">↓</a>
</section>
<?php endif; ?>
