<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \PartySupplies\PayOnAccount\Block\Info\Payonaccount
 */
?>
<dl class="payment-method payonaccount">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getInfo()->getAdditionalInformation()): ?>
    <?php endif; ?>
</dl>
