<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
<?php if ($_shipment && $_order && $trackCollection): ?>
    <br />
    <table class="shipment-track" style="border-collapse: collapse; width: 100%;">
        <thead>
        <tr>
            <th style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px 10px 10px 0; width: 50%;"><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px 10px 10px 0; width: 50%;"><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($trackCollection as $_item): ?>
            <tr>
                <td style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px 10px 10px 0; width: 50%;"><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                <td style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px 10px 10px 0; width: 50%;"><?= $block->escapeHtml($_item->getNumber()) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
