<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$minSaleQty = $tierPriceModel->getMinSaleQty();
$basePrice = $tierPriceModel->getBasePrice();
$basePriceFormatted = $tierPriceModel->getBasePriceFormatted();
$total = count($tierPrices);
?>
<?php if (count($tierPrices)) : ?>
    <?php
        $cheapestPrice = array_reduce(
            $tierPrices,
            function ($cheapest, $price) {
                if ($cheapest === null) {
                    return $price['price'];
                }
                return min($cheapest, $price['price']);
            }
        );
        $asLowAsPrice = $block->renderAmount(
            $cheapestPrice,
            [
                'include_container' => false,
                'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
            ]
        );
    ?>
    <div class="as-low-as">
        <span><?= __('as low as'); ?>:</span>
        <?= $asLowAsPrice; ?>
    </div>
    <table class="<?= /* @escapeNotVerified */ ($block->hasListClass() ? $block->getListClass() : 'prices-tier items') ?>">
        <tr>
            <th><?= __('Quantity'); ?></th>
            <?php if ($tierPrices[0]['price_qty'] > 2): ?>
                <th>1 - <?php echo $tierPrices[0]['price_qty'] - 1 ?></th>
            <?php elseif ($tierPrices[0]['price_qty'] == 2): ?>
                <th>1</th>
            <?php endif; ?>
            <?php foreach ($tierPrices as $index => $price) : ?>
                <?php if ($index == $total - 1): ?>
                    <?= "<th>" . $price['price_qty'] . "+" . "</th>"; ?>
                    <?php break; ?>
                <?php endif; ?>
                <?php
                    $toQty = $tierPrices[$index + 1]['price_qty'] - 1;
                    echo "<th>" . $price['price_qty'] . " - " . $toQty ."</th>";
                ?>
            <?php endforeach; ?>
        </tr>
        <tr> 
            <td class="item row-index"><?= __('Price (ea.)'); ?>:</td>
            <?php if ($tierPrices[0]['price_qty'] > 1): ?>
                <td><?= $basePriceFormatted ?></td>
            <?php endif; ?>
            <?php foreach ($tierPrices as $index => $price) : ?>
                <td class="item">
                        <?php
                            $priceAmountBlock = $block->renderAmount(
                                $price['price'],
                                [
                                    'price_id'          => $index,
                                    'id_suffix'         => '-' . $index,
                                    'include_container' => true,
                                    'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                                ]
                            );
                        ?>
                    <?= $priceAmountBlock; ?>
                </td>
            <?php endforeach; ?>
        </tr>
        <tr>
            <td class="item row-index"><?= __('You Save'); ?>:</td>
            <?php if ($tierPrices[0]['price_qty'] > 1): ?>
                <td><?= $tierPriceModel->getSavePercent($basePrice) . "%"; ?></td>
            <?php endif; ?>
            <?php foreach ($tierPrices as $index => $price) : ?>
                <td class="item">
                    <?= $tierPriceModel->getSavePercent($price['price']) . "%"; ?>
                </td>
            <?php endforeach; ?>
        </tr>
    </table>
<?php endif; ?>
