<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Archive
 */
?>

<?php
	$_months = $block->getMonths();
        $years = $block->getYearMonthWiseArchive();
        //echo '<pre>';var_dump($years);exit;
       // echo '<pre>';var_dump($block->postCount());exit;
        
?>
<?php if (count($_months)) { ?>
<div class="widget block block-archive" data-bind="scope: 'blog-archive'">
    <div class="block-title">
        <strong><?php echo __('Archive') ?></strong>
    </div>
   
    <div class=" archive panel-group mb-20">
    <div class="panel panel-default">
        <?php $i = 1; ?>
    	<?php foreach ($years as $key => $year) { ?>
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" href="#collapsel" class="text-capitalize collapsed" data-target="#yrfilter-<?= $i ?>" aria-expanded="false">
                    <span class="archive-toggle menu__icon--open" style="float:left;"></span> <?= $key; ?>
                    </a>

                </h2>
            </div>
             
            <div id="yrfilter-<?= $i ?>" class="filter-options-content  panel-collapse collapse" aria-expanded="false" >
                <ul class="list-group">
                <?php foreach($year as $monthkey => $post) { ?>
                    <li class="list-group-item"><a href="<?= $post['url'] ?>"><?= $monthkey ?>  (<?= $post['count'] ?>)</a></li>   
                <?php } ?>
                </ul>
            </div>
        <!--
            <div class="item">
                <a title="<?php //echo __('Archive %s', $title) ?>" class="archive-item-link" href="<?php //echo $block->getTimeUrl($time) ?>">
                    <?php //echo $title; ?>
                </a>
            </div>
        -->
        <?php $i++; ?>
        <?php } ?>
        </div>
        </div>
     
</div>
<?php } ?>
