stage:
  global:
    SCD_ON_DEMAND: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: "standard"
    SCD_COMPRESSION_TIMEOUT: 800
    VERBOSE_COMMANDS: "-vv"
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: true
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        max_concurrency: 60
  post-deploy:
    WARM_UP_PAGES:
      - "index.php"
      - "cms-page:*:1"
      - "customer/account/create/"
      - "customer/account/login/"

