stage:
  global:
    SKIP_HTML_MINIFICATION: true
    VERBOSE_COMMANDS: "-vv"
  build:
    SCD_STRATEGY: "compact"
    SCD_THREADS: 3
    SKIP_SCD: false
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_USE_SLAVE_CONNECTION: false
    CACHE_CONFIGURATION:
      _merge: true
      front_end:
        default:
          backend_options:
            connect_retries: 5
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        max_concurrency: 60
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 0
      consumers: []
  post-deploy:
    WARM_UP_PAGES:
      - "index.php"
      - "cms-page:*:1"
      - "customer/account/create/"
      - "customer/account/login/"
