stage:
  global:
    SKIP_HTML_MINIFICATION: true
    VERBOSE_COMMANDS: "-vv"
  build:
    SKIP_SCD: false
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
#    SEARCH_CONFIGURATION:
#      engine: mysql
    REDIS_USE_SLAVE_CONNECTION: true
    CACHE_CONFIGURATION:
      _merge: true
      front_end:
        default:
          backend_options:
            connect_retries: 5
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        max_concurrency: 60
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 0
      consumers: []
  post-deploy:
    WARM_UP_PAGES:
      - "https://mcprod.travers.com/index.php"
      - "https://mcprod.travers.com/customer/account/create/"
      - "https://mcprod.travers.com/customer/account/login/"
      - "https://mcprod.traverscanada.com/index.php"
      - "https://mcprod.traverscanada.com/customer/account/create/"
      - "https://mcprod.traverscanada.com/customer/account/login/"
      - "cms-page:*:default|canada"

