stage:
  deploy:
    MYSQL_USE_SLAVE_CONNECTION: true
    SEARCH_CONFIGURATION:
      engine: mysql
    REDIS_USE_SLAVE_CONNECTION: true
    CACHE_CONFIGURATION:
      _merge: true
      front_end:
        default:
          backend_options:
            connect_retries: 5
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        max_concurrency: 60
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 0
      consumers: []
  post-deploy:
    WARM_UP_PAGES:
      - "index.php"
      - "cms-page:*:1"
      - "customer/account/create/"
      - "customer/account/login/"
