version: "2.3"

services:

  # service discovery register
  registrator:
    image: gliderlabs/registrator
    command: "-cleanup=true consul://consul:8500"
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  # service discovery
  consul:
    image: consul
    command: "agent \
      -bootstrap-expect 1 \
      -server -bind 127.0.0.1 \
      -client 0.0.0.0 \
      -ui "
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8600:8600"
      - "8600:8600/udp"
    volumes:
      - consul-vol:/data/consul

volumes:
  consul-vol:

