version: '2.3'

services:

  varnish:
    image: '754729414608.dkr.ecr.us-east-2.amazonaws.com/varnish:v2.0'
    links:
      - app
    volumes_from:
      - app
    ports:
      - '80'
      - '443'
    labels:
      - 'traefik.frontend.rule=Host:travers.test'
      - traefik.domain=travers.test
    volumes: []

  app:
    image: "754729414608.dkr.ecr.us-east-2.amazonaws.com/travers-magento2:v0.0.1"
    cap_add:
      - SYS_PTRACE
    expose:
      - '80'
      - '443'
    links:
      - database
      - elasticsearch
      - rabbitmq
      - redis
      - smtp
    volumes_from:
      - database
      - elasticsearch
      - rabbitmq
      - redis
      - smtp

  database:
    image: 'percona:5.6'
    expose:
      - '3306'
    volumes:
      - target: /var/lib/mysql
        source: database-vol
        type: volume
      # Used if a database already exists
      # - target: /docker-entrypoint-initdb.d/
      #   source: ./files/db
      #   type: bind
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: magento_database
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: magento_password
    labels:
      - traefik.backend=travers.test

  elasticsearch:
    image: 'elasticsearch:2'
    expose:
      - '9200'
      - '9300'
    volumes:
      - target: /usr/share/elasticsearch/data
        source: elasticsearch-vol
        type: volume
    environment:
      - discovery.type=single-node
    labels:
      - traefik.backend=travers.test

  rabbitmq:
    image: rabbitmq
    expose:
      - '5672'
    volumes:
      - target: /var/lib/rabbitmq
        source: rabbitmq-vol
        type: volume
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /magento
    labels:
      - traefik.backend=travers.test

  redis:
    image: redis
    expose:
      - '6379'
    volumes:
      - target: /var/lib/redis
        source: redis-vol
        type: volume
    labels:
      - traefik.backend=travers.test

  smtp:
    image: mailhog/mailhog
    ports:
      - '8025'
    expose:
      - '1025'
    environment:
      - SMARTHOST_ADDRESS=mail.mysmtp.com
      - SMARTHOST_PORT=587
      - SMARTHOST_USER=myuser
      - SMARTHOST_PASSWORD=secret
      - SMARTHOST_ALIASES=*.mysmtp.com
    labels:
      - traefik.backend=travers.test

volumes:
  database-vol: null
  elasticsearch-vol: null
  rabbitmq-vol: null
  redis-vol: null
