<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
$wishlistBlock = $block->getLayout()->createBlock('Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist');
$isCustomerLoggedIn = $wishlistBlock->getWishlistHelper()->isCustomerLogIn();
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="javascript:void(0);"
       class="action towishlist <?= $isCustomerLoggedIn ? '' : 'wishlist-signin'?>"
       <?php if($isCustomerLoggedIn) : ?>
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       <?php else : ?>
       params='<?= $block->getAddToWishlistParams($block->getProduct()) ?>'
       <?php endif ?>
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
