<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>

    <div class="sharethis-inline-share-buttons"></div>

    <script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5ce553e47ff0c00012df0e65&product=inline-share-buttons' async='async'></script>

</div>
