<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
if ($_product->getTypeId() == \Magento\Bundle\Model\Product\Type::TYPE_CODE) {
    $wyomind_stock = $this->getLayout()->createBlock('Wyomind\AdvancedInventory\Block\Catalog\Product\Stock');
    $isInStock = json_decode($wyomind_stock->output($_product, "json"));
    $isSaleable = $isInStock->stock;
} else {
    $isSaleable = $_product->isSaleable();
}
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($isSaleable): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <button type="button" class="decreaseQty" onclick="decrementValue()"><span>-</span></button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button  type="button" class="increaseQty"  onclick="incrementValue()"><span>+</span></button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/javascript">
    var qty = document.getElementById("qty");
    function decrementValue(){
         if(!isNaN(qty.value) && qty.value > 1 ) {
             qty.value--;
         }
    }

    function incrementValue(){
         if(!isNaN(qty.value)) {
             qty.value++;
         }
    }
</script>