<?php
/**
 * Copyright © 2018 Vantiv, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<fieldset id="product_composite_configure_fields_subscription_plans" class="fieldset admin__fieldset <?php echo $block->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <legend class="legend admin__legend">
        <span><?php echo $block->escapeHtml(__('Subscription Options')) ?></span>
    </legend>
    <br>
    <div class="admin__field field" id="vantiv-subscription-plans-list">
        <label class="label admin__field-label">
            <span><?php echo $block->escapeHtml(__('Plan')) ?></span>
        </label>
        <div class="control admin__field-control">
            <?php foreach ($this->getPlans() as $plan): ?>
                <div class="field choice admin__field admin__field-option">
                    <input type="radio"
                           name="vantiv_subscription_plan"
                           id="vantiv_subscription_plan_<?php echo $block->escapeHtml($plan->getId()) ?>"
                           value="<?php echo $block->escapeHtml($plan->getId()) ?>" <?php if ($block->isPlanSelected($plan)): ?>checked<?php endif; ?>/>
                    <label class="label admin__field-label" for="vantiv_subscription_plan_<?php echo $block->escapeHtml($plan->getId()) ?>">
                        <span><?php /* @noEscape */ echo $block->getPlanTitle($plan); ?></span>
                    </label>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if ($block->getProduct()->getVantivRecurringAllowStart()): ?>
        <div class="admin__field field" id="vantiv-subscription-start-date">
            <label class="label admin__field-label">
                <span><?php echo $block->escapeHtml(__('Start Date')) ?></span>
            </label>
            <div class="control admin__field-control">
                <?php echo $block->getStartDateHtml() ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
