<?php
/**
 * Magedelight
 * Copyright (C) 2017 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Megamenu
 * @copyright Copyright (c) 2017 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$columnsLimit = $block->getColumnsLimit() ? : 0;  
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit, false) ?>
<?php $_mobMenu = $block->getHtml('level-top', 'submenu', $columnsLimit, true) ?>
<?php $menuDesign = $block->getMenuDesign(); ?>

<div class="menu-container horizontal-menu">
    <div data-action="navigation" class="menu <?= /* @noEscape */ $menuDesign; ?> <?php
    if ($block->isSticky() === '1') :
        echo "stickymenu";
    endif;
            ?>">
        <ul>
            <?= /* @noEscape */ $_menu; ?>
        </ul>
        <?php
        echo $block->menuStyleHtml();
        ?>
    </div>
</div>

<script type="text/javascript">
    var animation_time = '<?= /* @noEscape */ $block->animationTime(); ?>';
    require(['jquery'], function ($) {
        var nav = $('.horizontal-menu');
        if (nav.length) {
            $('body').addClass('mega-menu');
            var stickyHeaderTop = nav.offset().top;
            $(window).scroll(function () {
                if ($(window).width() >= 768) {
                    if ($(window).scrollTop() > stickyHeaderTop) {

                        if ($('.horizontal-menu .stickymenu').hasClass('vertical-right')) {
                            var outerWidth = $('.section-items.nav-sections-items').width();
                            var innerWidth = $('.menu-container.horizontal-menu').width();
                            var rightMargin = ((outerWidth - innerWidth) / 2) + 'px';
                            $('.horizontal-menu .stickymenu').css({position: 'fixed', top: '0px', right: rightMargin});
                        } else {
                            $('.horizontal-menu .stickymenu').css({position: 'fixed', top: '0px'});
                        }

                        $('.stickyalias').css('display', 'block');
                    } else {
                        $('.horizontal-menu .stickymenu').css({position: 'static', top: '0px'});
                        $('.stickyalias').css('display', 'none');
                    }
                }
            });

            $('.section-item-content .menu-container.horizontal-menu .menu > ul li.dropdown').each(function (e) {
                $(this).children('a').after('<span class="plus"></span>');
                if($(this).find('ul a').length) {
                    $(this).addClass('parent');
                }
            });

            $('.section-item-content .menu-container.horizontal-menu .menu > ul li.dropdown span.plus').click(function (e) {
                $(this).siblings('a').toggleClass('active');
                $(this).toggleClass('active').siblings('ul').slideToggle('500');
            });
        }

        if($(".section-item-content .menu-container .menu > ul > li").length > 4) {
            $('.section-item-content .menu-container').addClass('menu-extended');
        }

        $(".section-item-content .menu-container .menu > ul > li.dropdown").hover(function () {
            $('body').toggleClass("menu-hovered");
        });
    });
</script>

<div data-bind="scope: 'customer'" class="user-prof customer-name">
    <!-- ko if: customer().firstname  -->
    <span class="mob greet user-info">
        <span class="customer-logo"></span>
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Hello, %1!', '%1')) ?>').replace('%1', customer().firstname)">
        </span>
    </span>             
    <!-- /ko -->
    <!-- ko ifnot: customer().firstname  -->
    <span class="mob greet user-info">
        <span class="customer-logo"></span>
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Hello, User!')) ?>')">
        </span>
    </span>
    <!-- /ko -->
</div>
<div id="mobile-menu" class="mobile-menu">   
    <ul class="menu-list">
        <li>
            <a href="<?php echo $block->getBaseUrl().'customer/account/'?>"><?= $block->escapeHtml(__('My Account')) ?></a>
            
            <ul data-bind="scope: 'customer'" class="customer-name">               
                <!-- ko if: customer().firstname  -->
                <li>
                    <a href="<?php echo $block->getBaseUrl().'customer/account/'?>"><?= $block->escapeHtml(__('My Account')) ?></a>
                </li>
                <li class="link wishlist">
                    <a href="<?php echo $block->getBaseUrl().'wishlist/'?>">
                        <?= $block->escapeHtml(__('My Wishlist')) ?>                        
                    </a>
                </li>
                <li class="authorization-link">
                    <a href="<?php echo $block->getLogoutUrl() ?>" data-post='<?= /* @noEscape */ $block->getPostParams() ?>'><?= $block->escapeHtml(__('Sign Out')) ?></a>
                </li>
                <!-- /ko -->
                <!-- ko ifnot: customer().firstname  -->
                <li> 
                    <a href="<?php echo $block->getBaseUrl().'customer/account/login'?>">
                        <?= $block->escapeHtml(__('Sign In')) ?>                    
                    </a>
                </li>
                <li> 
                    <a href="<?php echo $block->getBaseUrl().'customer/account/create'?>">
                        <?= $block->escapeHtml(__('Create Account')) ?>
                    </a> 
                </li>
                <!-- /ko -->            
            </ul>                    
        </li>                             
        <?= /* @noEscape */ $_mobMenu; ?>
        <li> 
            <a href="<?php echo $block->getBaseUrl().'shop-by-brand'?>">
                <?= $block->escapeHtml(__('Our Brands')) ?>
            </a> 
            <ul>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'shop-by-brands/earthlite.html'?>">
                        <?= $block->escapeHtml(__('Earthlite')) ?>
                    </a> 
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'shop-by-brands/stronglite.html'?>">
                        <?= $block->escapeHtml(__('Stronglite')) ?>
                    </a> 
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'shop-by-brands/inner-strength.html'?>">
                        <?= $block->escapeHtml(__('Inner Strength')) ?>
                    </a> 
                </li>
            </ul>
        </li>
        <li>
            <span>Our Company</span>
            <ul class="links">
                <li>
                    <a href="<?php echo $block->getBaseUrl().'about-earthlite' ?>" title="About Us">
                        <?= $block->escapeHtml(__('About Us')) ?>
                    </a> 
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'earthlite-difference' ?>" title="Earthlite Difference">
                        <?= $block->escapeHtml(__('Earthlite Difference')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'guiding-principles' ?>" title="Guiding Principles">
                        <?= $block->escapeHtml(__('Guiding Principles')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'from-our-founder' ?>" title="From Our Founder">
                        <?= $block->escapeHtml(__('From Our Founder')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'press-releases' ?>" title="Press Releases"><?= $block->escapeHtml(__('Press Releases')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'blog' ?>" title="blog">
                        <?= $block->escapeHtml(__('Blog')) ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <span>Customer Service</span>
            <ul class="links">
                <li>
                    <a href="<?php echo $block->getBaseUrl().'contact' ?>" title="Contact Us">
                        <?= $block->escapeHtml(__('Contact Us')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'warranty' ?>" title="warranty">
                        <?= $block->escapeHtml(__('Warranty')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'returns' ?>" title="Returns">
                        <?= $block->escapeHtml(__('Returns')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'shipping-info' ?>" title="Shipping Info">
                        <?= $block->escapeHtml(__('Shipping Info')) ?>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <span>Resources</span>
            <ul class="links">
                <li>
                    <a href="<?php echo $block->getBaseUrl().'faqs' ?>" title="FAQs">
                        <?= $block->escapeHtml(__('FAQs')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'help-desk' ?>" title="Help Desk">
                        <?= $block->escapeHtml(__('Help Desk')) ?>
                    </a>
                </li>
                <li>
                    <a href="https://online.pubhtml5.com/byrl/ioet/" target="blank" title="Our Catalogs">
                       <?= $block->escapeHtml(__('Our Catalog')) ?>
                   </a>
               </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'upholstery-options' ?>" title="Upholstery Options">
                        <?= $block->escapeHtml(__('Upholstery Info')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'stain-options' ?>" title="Stain & Lacquer Options">
                        <?= $block->escapeHtml(__('Stain & Lacquer Info')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'cleaning-instructions' ?>" title="Cleaning Instructions">
                        <?= $block->escapeHtml(__('Cleaning Instructions')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'privacy' ?>" title="Earthlite Privacy & Security">
                        <?= $block->escapeHtml(__('Security & Privacy')) ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $block->getBaseUrl().'policy' ?>" title="General Policies">
                        <?= $block->escapeHtml(__('Our Policy')) ?>
                    </a>
                </li>
        </ul>
        </li>                
        <span class="phone-sec">
            <a href="tel:800-872-0560">800-872-0560</a>
        </span>
    </ul>
</div>

<script type="text/javascript">
	require(['jquery', 'mmenu'], function ($) 
	{
		$(document).ready(function(){
		  $('#mobile-menu').mmenu({
                extensions: ['effect-slide-menu'],
                    searchfield: false,
                    counters: false,
                    navbar: {
                        title: ['']
                    },
                    offCanvas: {
                        position: "left"
                    },
                    navbars: [{
                            position: 'top',
                            content: [
                                'prev',
                                'title',
                                'close'
                            ]
                        }]
                });        
		});
                
        $('.user-prof').detach().insertAfter('.mobile-menu .mm-navbar-top-1 .mm-title');
                
	});
</script>
 <script type="text/x-magento-init">
  {
    ".customer-name": {
      "Magento_Ui/js/core/app": {
        "components": {
          "customer": {
            "component": "Magento_Customer/js/view/customer"
          }
        }
      }
    }
  }
  </script>