<?php
if ($block->getTopCategoryConfig()) {
    $data = $block->getCatalogData();
    $catalogData = $data['catalogData'];
    $mediaBaseUrl = $data['mediaBaseUrl'];
    if (isset($catalogData) && count($catalogData) > 0) {
       ?>
        <section class="category-slider-wrap py-10">
        <h2 class="mb-6">
            <?php echo $block->getTitle() ?>
        </h2>

        <div class="products wrapper grid products-grid category-slider">
            <ol class="products list items product-items">
                <?php foreach ($catalogData as $key => $cat) { ?>
                <li class="item product product-item">
                <?php
                    $categoryName = str_replace(' ', '-', $cat->getName());
                    $CategoryNameSplChar = preg_replace('/[^A-Za-z0-9\-]/', '', $categoryName);
                    $categoryImageURL = $cat->getImageUrl() ? $cat->getImageUrl() : $block->getViewFileUrl('Earthlite_TopCategory::images/category_placeholder.png');
                    ?> 
                    <div class="product-item-info">
                            <a class="product-item-link" href="<?= $block->escapeUrl($cat->getUrl()) ?>" tabindex="0">
                            <div class="product details product-item-details">
                                <img class="product-image" src="<?= $categoryImageURL ?>" alt="<?= $categoryName ?>">
                                <strong class="product name product-item-name">
                                    <?= $categoryName ?>
                                </strong>
                            </div>
                        </a>
                </li>
                <?php } ?>
                </ol>

                <div class="progress-bar">
                    <div class="progress-handle" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
        </div>
    </section>
    <?php } }?>


    <script type="text/javascript">
    require(['jquery', 'slick'], function ($) {
    "use strict";
    $(function () {

        let $catSlider = $('.category-slider .product-items');
        var $progressBar = $('.progress-handle');

        $catSlider.slick({
            infinite: false,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 1,
            responsive: [
                {
                    breakpoint: 1300,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 992,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        arrows: false,
                        slidesToShow: 1,
                        slidesToScroll: 1
                    }
                }

            ]
        });

        $catSlider.on('beforeChange', function(event, slick, currentSlide, nextSlide) {   
            var calc = ( (nextSlide) / (slick.slideCount - 1) ) * 100;
            $progressBar.attr('aria-valuenow', calc );
            //$progressBar.css('left',  + calc+ '%');
            $progressBar.css('-webkit-transform',  'translateX(' + calc+ '%)');
        });

        $catSlider.on('afterChange', function (event, slick, currentSlide) {
            $('.category-slider .slick-list').addClass('pad');
            if (currentSlide === 0) {
                $('.category-slider .slick-list').removeClass('pad');
            }

            if (currentSlide !== 0) {
                $('.category-slider .slick-list').removeClass('first');
            }

            if (slick.slideCount === currentSlide + 1) {
                $('.category-slider .slick-list').addClass('last').removeClass('first');
            }

            if (slick.slideCount !== currentSlide + 1) {
                $('.category-slider .slick-list').removeClass('last');
            }
        });
    });
});

</script>