<?php
/** @var SomethingDigital\ReactPlp\ViewModel\ReactPlp $viewModel */
$viewModel = $block->getViewModel();
?>

<div id="react-plp"></div>

<script type="text/javascript">
    require(['jquery'], function ($) {
    $(function () {
        var props = <?php echo $viewModel->getJsProps() ?>;
        window.props = props;
        renderReactPLP(document.getElementById('react-plp'), props);
    });
});
</script>
