<?php
/** @var SomethingDigital\ReactPlp\ViewModel\ReactPlp $viewModel */
$viewModel = $block->getViewModel();
?>

<div id="react-plp"></div>

<script type="text/javascript">
    require(['jquery'], function ($) {
    $(function () {
        var props = <?php echo $viewModel->getJsProps() ?>;
        renderReactPLP(document.getElementById('react-plp'), props);

        var searchQuery = jQuery('#current_url').val();
        var query = searchQuery.split('?');
        if(query[1]){
            var newurl = window.location.protocol + "//" + window.location.host + window.location.pathname +'?'+query[1];
            window.history.pushState({ path: newurl }, '', newurl);
        }
    });
});
</script>
