<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\ProductAlert\Block\Email\Stock */
$unSubscribeStatus = false;
?>
<?php if ($_products = $block->getProducts()) : ?>
    <p><?= $block->escapeHtml(__('In stock alert! We wanted you to know that these products are now available:')) ?></p>
    <table>
        <?php foreach ($_products as $_product) : ?>
            <tr>
                <?php 
                    if ($_product->getVisibility() == 1) {
                        $product = $this->getParentProduct($_product->getId());
                    } else {
                        $product = $_product;
                    }
                ?>
                <td class="col photo">
                    <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>" title="<?= $block->escapeHtmlAttr($_product->getName()) ?>" class="product photo">
                        <?= $block->getImage($product, 'product_thumbnail_image', ['class' => 'photo image'])->toHtml() ?>
                    </a>
                </td>
                <td class="col item">
                    <p>
                        <strong class="product name">
                            <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>"><?= $block->escapeHtml($product->getName()) ?></a>
                        </strong>
                    </p>
                    <?php if ($shortDescription = $block->getFilteredContent($product->getShortDescription())) : ?>
                        <p><small><?= /* @noEscape */ $shortDescription ?></small></p>
                    <?php endif; ?>
                    <?=
                    $block->getProductPriceHtml(
                            $_product, \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE, \Magento\Framework\Pricing\Render::ZONE_EMAIL, [
                        'display_label' => __('Price:')
                            ]
                    );
                    ?>
                    <?php
                    if ($_product->getCustomerGroupId() != 0){
                        $unSubscribeStatus = true;
                        ?>
                        <p><small><a href="<?= $block->escapeUrl($block->getProductUnsubscribeUrl($_product->getId())) ?>"><?= $block->escapeHtml(__('Click here to stop alerts for this product.')) ?></a></small></p>
                    <?php } ?>
                </td>
            </tr>
    <?php endforeach; ?>
    </table>
    <?php if ($unSubscribeStatus) : ?>
        <p><a href="<?= $block->escapeUrl($block->getUnsubscribeUrl()) ?>"><?= $block->escapeHtml(__('Unsubscribe from all stock alerts')) ?></a></p>
    <?php endif; ?>
<?php endif; ?>

