<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
    <?php if ($rating):?>
    <div class="rating-summary">
        <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
        <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating) ?>%">
            <span style="width:<?= $block->escapeHtmlAttr($rating) ?>%"><span><?= $block->escapeHtml($rating) ?>%</span></span>
        </div>
    </div>
    <?php endif;?>
    <div class="reviews-actions">
        <a class="action view"
           id="product-view-reviews"
           href="<?= $block->escapeUrl($url) ?>"
           onclick="dataLayer.push({'event': 'product_reviewsShort'});">
            <?= $block->escapeHtml($block->getReviewsCount()) ?>
            <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
        </a>
    </div>
</div>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>
<div class="product-reviews-summary short empty">
    <div class="reviews-actions">
        <a class="action add"
           id="product-add-reviews"
           href="<?= $block->escapeUrl($urlForm) ?>"
           onclick="dataLayer.push({'event': 'product_reviewsShort'});">
            <?= $block->escapeHtml(__('Be the first to review this product')) ?>
        </a>
    </div>
</div>
<?php endif; ?>
