<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation d-mobile" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class='level0 level-top'>
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bulk_order')->toHtml(); ?>
        </li>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>

<nav class="navigation d-desktop" id="menu">
    <a class="menu-close" href="#mm-0"><span class="mm-sronly">Close menu</span></a>
    <ul >
        <li class='level0 level-top'>
        <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bulk_order')->toHtml(); ?>
        </li>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
