<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$burgerStatus = $block->getConfigBurgerStatus();
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
</nav>


<script type="text/javascript">
    require(['jquery'], function ($) {
        /* Check burger menu is enable */
        var burgerStatus = <?php echo $burgerStatus; ?>;
        var html = $('html');
        if (burgerStatus) {
            html.addClass('md-burger-menu');
        } else {
            html.removeClass('md-burger-menu');
        }

        }
    );
</script>