<?php
/**
 * Copyright © 2018 Vantiv, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Vantiv\Payment\Block\Recurring\Customer\Subscriptions\Edit
 */
?>
<form class="vantiv-subscription-edit" action="<?php echo $block->getSaveUrl() ?>" method="post" id="vantiv-subscription-edit" enctype="multipart/form-data" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <fieldset class="fieldset subscription">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php echo __('Subscription Information') ?></span></legend>
        <div class="field subscription-id">
            <label class="label" for="subscription_id"><span><?php echo $this->escapeHtml(__('Subscription ID')) ?></span></label>
            <div class="control">
                <span><?= $this->escapeHtml($block->getSubscription()->getVantivSubscriptionId()); ?></span>
            </div>
        </div>
        <div class="field product-name">
            <label class="label" for="product_name"><span><?php echo $this->escapeHtml(__('Product Name')) ?></span></label>
            <div class="control">
                <span><?= $this->escapeHtml(__($block->getSubscription()->getProductName())); ?></span>
            </div>
        </div>
        <?php if($block->getPlans()) : ?>
            <div class="field plan">
                <label class="label" for="plan"><span><?php echo $this->escapeHtml(__('Payment Plan')) ?></span></label>
                <?php foreach ($block->getPlans() as $plan): ?>
                    <div class="field choice">
                        <input type="radio"
                               name="plan_id"
                               id="plan_id_<?php echo $plan->getId() ?>"
                               value="<?php echo $plan->getId() ?>"
                               <?php if ($block->isPlanSelected($plan)): ?>checked<?php endif; ?>/>
                        <label class="label" for="plan_id_<?php echo $plan->getId() ?>">
                            <span><?php echo $block->getPlanTitle($plan); ?></span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <?php if ($block->getSubscription()->getDiscountCollection()->getSize()): ?>
                    <p class="note">
                        <strong><?php echo $block->escapeHtml(__('If plan changed, all existing subscription discounts will be automatically removed')); ?></strong>
                    </p>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </fieldset>
    <fieldset class="fieldset billing">
       <legend class="legend"><span><?php echo __('Billing Information') ?></span></legend>
        <div class="field firstname required">
            <label class="label" for="firstname"><span><?php echo $this->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input type="text" name="firstname" data-validate="{required : true, maxlength : 25}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getFirstname()) ?>" id="firstname" class="input-text" title="<?php echo $this->escapeHtml(__('First Name')) ?>"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?php echo $this->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input type="text" name="lastname" data-validate="{required : true, maxlength : 25}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getLastname()) ?>" id="lastname" class="input-text" title="<?php echo $this->escapeHtml(__('Last Name')) ?>"/>
            </div>
        </div>
        <div class="field street required">
            <label class="label" for="street"><span><?php echo $this->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <input type="text" name="street" data-validate="{required : true, maxlength : 35}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getStreet()) ?>" id="street" class="input-text" title="<?php echo $this->escapeHtml(__('Address')) ?>"/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" data-validate="{required : true, maxlength : 35}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getCity()) ?>" title="<?php echo __('City') ?>" class="input-text" id="city" title="<?php echo __('City') ?>"/>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php echo __('State/Province') ?>" class="validate-select">
                    <option value=""><?php echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getRegion()) ?>"  title="<?php echo __('State/Province') ?>" class="input-text required-entry"/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" data-validate="{required : true, maxlength : 20}" value="<?php echo $block->escapeHtml($block->getSubscription()->getBillingAddress()->getPostcode()) ?>" title="<?php echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international"/>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?php echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $this->getLayout()->createBlock('\Magento\Directory\Block\Data')->getCountryHtmlSelect($block->getSubscription()->getBillingAddress()->getCountryId()) ?>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset payment">
        <legend class="legend"><span><?php echo __('Payment Information') ?></span></legend>
        <div class="field">
            <div class="control">
                <input type="radio"
                       name="vantiv_subscription_payment"
                       id="vantiv_subscription_payment_no_change"
                       value="-1"
                       checked />
                <label class="label" for="vantiv_subscription_payment_no_change">
                    <span><?php echo $block->escapeHtml(__('Do not modify payment')) ?></span>
                </label>
            </div>
            <?php /** @var \Magento\Vault\Model\PaymentToken $payment */ ?>
            <?php foreach($this->getSavedPayments() as $payment) : ?>
                <div class="control">
                    <?php $details = $block->getDetails($payment); ?>
                    <?php $icon = $block->getPaymentIcon($payment); ?>
                    <input type="radio"
                           name="vantiv_subscription_payment"
                           id="vantiv_subscription_payment_<?php echo $payment->getId(); ?>"
                           value="<?php echo $payment->getId() ?>"
                           title="<?php echo $block->escapeHtml('Existing ') . $details['ccType'] . $details['ccLast4']; ?>" />
                    <?php if($icon) : ?>
                        <img src="<?php echo $block->escapeUrl($icon['url']); ?>"
                             width="<?php echo $block->escapeHtml($icon['width']); ?>"
                             height="<?php echo $block->escapeHtml($icon['height']); ?>"
                             class="payment-icon">
                    <?php else : ?>
                        <span><?php echo $block->escapeHtml($details['ccType']); ?></span>
                    <?php endif; ?>
                    <span><?php echo $block->escapeHtml(__('ending'));?></span>
                    <span><?php echo $block->escapeHtml($details['ccLast4']); ?></span>
                    (<span><?php echo $block->escapeHtml(__('expires'));?></span>:
                    <span><?php echo $block->escapeHtml(
                            $details['ccExpMonth'] . '/' . $details['ccExpYear']
                        ); ?></span>)
                </div>
            <?php endforeach; ?>
            <div class="control">
                <input type="radio"
                       name="vantiv_subscription_payment"
                       id="vantiv_subscription_payment_new_card"
                       value="-2" />
                <label class="label" for="vantiv_subscription_payment_new_card">
                    <span><?php echo $block->escapeHtml(__('Use new credit card')) ?></span>
                </label>
                <div id="new_card" style="display: none;">
                    <div id="payframe"></div>
                    <input type="hidden" id="vantiv-paypage-registration-id" name="paypage_registration_id" />
                    <input type="hidden" id="vantiv-cc-type" name="cc_type" />
                </div>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button
                    type="submit"
                    class="action save primary"
                    data-action="save-subscription"
                    title="<?php echo $block->escapeHtml(__('Save Subscription')); ?>"
            >
                <span><?php echo $block->escapeHtml(__('Save Subscription')); ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#payframe": <?php echo $block->getCcFormMageInitJson(); ?>,
        "#vantiv-subscription-edit": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#vantiv-subscription-edit",
                "regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php echo $block->getSubscription()->getBillingAddress()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
