<?php
/**
 * @var $block \Magento\ProductAlert\Block\Product\View
 * @var $viewModel \Earthlite\ProductAlert\ViewModel\CustomerSession
 */
$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
?>
<?php if($viewModel->isLoggedIn()): ?>
    <div class="product alert <?= $block->getHtmlClass() ?>">
        <a href="<?= $block->escapeUrl($block->getSignupUrl()) ?>"
        title="<?= $block->escapeHtmlAttr(__($block->getSignupLabel())) ?>" class="action alert">
            <?= $block->escapeHtml(__($block->getSignupLabel())) ?>
        </a>
    </div>
<?php else: ?>
    <form class="form notify-me" action="<?= $block->escapeUrl($block->getUrl('guestalert/add/stockalert')) ?>" id="stock-alert" method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Sign up for stock alert')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    <input name="product_id" id="product_id" value="<?= $product->getId() ?>" type="hidden"/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Notify Me')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Notify Me')) ?></span>
                </button>
            </div>
        </div>
    </form>
<?php endif; ?>
