<?php
/**
 * @var $block \Magento\ProductAlert\Block\Product\View
 * @var $viewModel \Earthlite\ProductAlert\ViewModel\CustomerSession
 */
$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
$customerId = $viewModel->isLoggedIn();
?>
<div id="notify-block" style="display: <?= $viewModel->displayBlock()?>">
    <form class="form notify-me" action="<?= $block->escapeUrl($block->getUrl('guestalert/add/stockalert')) ?>" id="stock-alert" method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <?php if (!$customerId): ?>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Sign up for stock alert')) ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <div class="control">
                    <input name="product_id" id="parent_product_id" value="<?= $product->getId() ?>" type="hidden"/>
                    <input name="child_product_id" id="child_product_id" value="<?= $product->getId() ?>" type="hidden"/>
                </div>
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Notify Me')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Notify Me')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>


