<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem() ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>" style="font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px; border-top: 1px solid #d8dde7;">
        <p class="product-name" style="margin-top: 0; font-weight: 700; margin-bottom: 5px; color: #001842;"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku" style="margin-top: 0; margin-bottom: 0;"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options" style="margin-top: 0; margin-bottom: 0; padding-left: 20px;">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt style="font-weight: 700; margin-top: 0; margin-bottom: 0; padding-bottom: 0;"><strong style="font-weight: 700;"><em style="font-style: normal;"><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd style="margin-top: 0; margin-left: 0; margin-bottom: 0; padding-bottom: 0; padding-left: 10px;">
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty" style="font-weight: 600; font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; vertical-align: top; padding: 10px; border-top: 1px solid #d8dde7; text-align: center;"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
</tr>

