<div class="menu-wrap h-blk">
    <span class="menu-icon hidden-ms">
    	<span class="icon-bar icon-1"></span>
    	<span class="icon-bar icon-2"></span>
    	<span class="icon-bar icon-3"></span>
    </span>
    <ul class="menu-navigation">
        <li><a href="#">Main Page</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">FAQ</a></li>
		<li><a href="<?php echo $block->getUrl('customer/account/login') ?>">Login</a></li>
    </ul>
</div>

