<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->create('Magento\Store\Model\StoreManagerInterface');
$websiteId = $storeManager->getStore()->getWebsiteId();
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create()
            ->addAttributeToSelect('*')
            ->setPageSize(1);
$collection->addWebsiteFilter($websiteId);
$productId = $collection->getFirstItem();
$url=$objectManager->get('Magento\Checkout\Helper\Cart')->getAddUrl($productId);
?>
<div class="content-container">
	<div class="content-top">
	    <div class="container">
	        <div class="content-inner_blk">
		        <div class="img-blk">
					<a href="">
	                    <img src="<?php echo $block->getViewFileUrl('images/coin.png'); ?>" alt="" class="">
					</a>
                </div>
                <div class="price-blk">
		            <div class="price">$79<span class="price-sub"><span class="up">95</span><span class="down">+s&h</span></div>
					<form data-role="tocart-form" action="<?php echo $url; ?>" method="post"> 
					    <?php echo $block->getBlockHtml('formkey')?>
		 		    	<button type="submit" title="Add to Cart" class="btn-buy btn btn-link">
		       			<span>Buy Now</span>
		     			</button>
		 			</form>
                </div>
                <div class="amc-blk">
                	<img src="<?php echo $block->getViewFileUrl('images/amc_tv.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
	<div class="content-bottom">
		<div class="container">
			<div class="content-inner_blk">
      			<div class="content-blk">
		            <h2>2018 The Walking Dead “All Out War” Silver Coin</h2>
		            <ul class="desc">
		                <li>Commemorating Season 8 of AMC’s <br/> The Walking Dead - “All Out War”</li>
		                <li>One troy ounce of .999 Fine Silver</li>
		                <li>Cook Island two dollar legal tender</li>
		                <li>Includes custom box and coin holder</li>
		            </ul>
                    <div class="img-blk">
						<a href="">
                            <img src="<?php echo $block->getViewFileUrl('images/coin.png'); ?>" alt="" />
						</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




