<div class="menu-wrap h-blk">
    <span class="menu-icon hidden-ms">
    	<span class="icon-bar icon-1"></span>
    	<span class="icon-bar icon-2"></span>
    	<span class="icon-bar icon-3"></span>
    </span>
    <ul class="menu-navigation">
        <li><a target="_blank" href="http://shopcsntv.com/">Main Page</a></li>
        <li><a href="/walking-deadcoin-aboutus">About Us</a></li>
        <li><a href="/walking-deadcoin-contactus">Contact Us</a></li>
        <li><a href="/walking-deadcoin-faq">FAQ</a></li>
	<li><a href="<?php echo $block->getUrl('customer/account/login') ?>">Login</a></li>
    </ul>
</div>

