<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\View $block */
$post = $block->getPost();
/** @var Earthlite\Blog\ViewModel\Blog $viewModel */
$viewModel = $block->getViewModel();
?>

<div class="blog__post-view">
    <?php if ($post->getFeaturedImageUrl()): ?>
        <img src="<?= $post->getFeaturedImageUrl() ?>" alt="<?= $post->getName() ?>" class="blog__post-featured-image"/>
    <?php endif ?>

    <?= $block->getPostContent() ?>

    <?= $this->getPostMetaFooter()->toHtml() ?>
    <div class="text-right">
    <a href="<?= $viewModel->getBlogBackUrl() ?>" class="action primary"><i class="icon-chevron-left align-middle"></i>  <?= $block->escapeHtml(__('Back to Blogs'))?></a>
    </div>
    <?= $this->getChildHtml('blog.post.related.posts') ?>

    <?= $this->getChildHtml('blog.post.related.products') ?>

    <?= $this->getChildHtml('blog.post.comments') ?>
</div>
