<?php
/**
 * Copyright © 2015 ziffitycommerce. All rights reserved.
 */
?>
<div class="header-promo clearfix">
    <div class="container">
    <div class="col-sm-9 text-center">
        <?php $storeInfo = $block->getConfigValue();
        echo $storeInfo['welcome_header'];
        ?>
    </div>
    <div class="col-sm-3 text-center">
<?php echo $storeInfo['store_timings']; ?> 
        <div class="ph">
            <strong> <?php echo $storeInfo['store_phone']; ?></strong>
        </div>
    </div>
    </div>  
</div>