<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $stockStatus = $block->getViewModel()->getStockStatus() ?>
<?php if ($block->displayProductStockStatus()): ?>
    <p class="stock available" title="<?= /* @escapeNotVerified */ __('Availability:') ?>">
        <span><?= /* @escapeNotVerified */ $stockStatus ?></span>
        <span class="stock-info-popup-trigger"><?= __('Check Locations') ?></span>
    </p>
<?php endif; ?>
