<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $data = $block->getRequest()->getPost("creditmemo"); ?>
<?php $block->setPriceDataObject($_item); ?>
<tr>
    <td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?php echo $block->getColumnHtml($_item, 'price'); ?>
    </td>
    <td class="col-ordered-qty"><?php echo $block->getColumnHtml($_item, 'qty') ?></td>
    <?php //if ($block->canParentReturnToStock($_item)) :  ?>
    <td class="col-return-to-stock">
        <?php //if ($block->canReturnItemToStock($_item)) : ?>

        <select name='creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>][back_to_stock]'>
            <option value='0'>No</option>
            <?php foreach ($block->getPos() as $pos) : ?>
                <option <?php if ($data['items'][$_item->getOrderItemId()]['back_to_stock'] == $pos->getPlaceId()) echo "selected"; ?> value="<?php echo $pos->getId(); ?>"><?php echo $pos->getName(); ?></option>
            <?php endforeach; ?>
        </select>
        <label class="admin__field-label"></label>
        <?php //endif;  ?>
    </td>
    <?php //endif; ?>
    <td class="col-refund col-qty">
        <?php if ($block->canEditQty()) : ?>
            <input type="text"
                   class="input-text admin__control-text qty-input"
                   name="creditmemo[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>][qty]"
                   value="<?php /* @escapeNotVerified */ echo $_item->getQty() * 1 ?>"/>
               <?php else : ?>
                   <?php /* @escapeNotVerified */ echo $_item->getQty() * 1 ?>
               <?php endif; ?>
    </td>
    <td class="col-subtotal">
        <?php echo $block->getColumnHtml($_item, 'subtotal'); ?>
    </td>
    <td class="col-tax-amount"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discont"><?php /* @escapeNotVerified */ echo $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $block->getColumnHtml($_item, 'total'); ?>
    </td>
</tr>
