<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $viewModel = $block->getData('qtyData'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <button type="button" id="dec" class="decreaseQty"><span>-</span></button>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       <?php if($viewModel): ?>
                       data-advanced-inventory = "<?= $block->escapeHtml($viewModel->getQuantityValidators($_product->getId(), $_product->getStore()->getWebsiteId())) ?>"
                       <?php endif; ?>
                       />
                <button type="button" id="inc" class="increaseQty"><span>+</span></button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <?php if ($viewModel->isCallForPrice($_product)): ?>
              <button type="submit"
                      title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                      class="action primary tocart"
                      id="product-addtocart-button">
                  <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
              </button>
            <?php else: ?>
              <button type="button"
                      title="<?= $block->escapeHtml(__('Call For Price')) ?>"
                      class="action primary">
                  <span><?= $block->escapeHtml(__('Call For Price')) ?></span>
              </button>
            <?php endif; ?>
        </div>
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {},
            "Magento_Theme/js/action": {}
        }
    }
</script>
