<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Template for displaying product price at product view page, gift registry and wish-list
 *
 * @var $block \Magento\Msrp\Pricing\Render\PriceBox
 */
?>
<?php

/** @var Magento\Msrp\Pricing\Price\MsrpPriceInterface $priceType */
$priceType = $block->getPrice();

/** @var $product \Magento\Catalog\Model\Product */
$product = $block->getSaleableItem();
$productId = $product->getId();

$amount = $block->getMsrpPriceCalculator()->getMsrpPriceValue($product);

$msrpPrice = $block->renderAmount(
    $priceType->getCustomAmount($amount),
    [
        'price_id' => $block->getPriceId() ? $block->getPriceId() : 'old-price-' . $productId,
        'include_container' => false,
        'skip_adjustments' => true
    ]
);
$priceElementIdPrefix = $block->getPriceElementIdPrefix() ? $block->getPriceElementIdPrefix() : 'product-price-';
?>

<?php if ($amount): ?>
        <p class="price-head caps">msrp : <span class="get-info msrp-value"><?= $msrpPrice ?></span></p>
        <p class="price-head">each price : <span class="get-info each-value"><?= $block->getRealPriceHtml() ?></span></p>
<?php endif; ?>
