<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/
 // @codingStandardsIgnoreFile ?>
<div class="aw-extensions-menu admin__action-dropdown-wrap">
    <button class="admin__action-dropdown" title="Menu" data-toggle="dropdown" data-mage-init='{"dropdown":{}}'>
        <span class="admin__action-dropdown-text"><?php /* @noEscape */ echo $this->getCurrentItemTitle();?></span>
    </button>
    <ul class="admin__action-dropdown-menu">
        <?php foreach($this->getItems() as $key => $item):?>
            <?php $class = array_key_exists('class', $item)? $item['class']: '';?>
        <li class="action-dropdown-menu-action<?php /* @noEscape */ echo ($key==$this->getCurrentItemKey()?' current disabled':'');?> <?php /* @noEscape */ echo array_key_exists('class', $item)? $item['class']: '';?>">
            <a href="<?php /* @noEscape */ echo $item['url'];?>" data-ui-id="aw-extensions-<?php /* @noEscape */ echo $key;?>" title="<?php /* @noEscape */ echo $item['title'];?>"
                <?php /* @noEscape */ echo array_key_exists('target', $item)?'target="' . $item['target'] . '"':'';?>><?php /* @noEscape */ echo $item['title'];?>
            </a>
        </li>
        <?php endforeach;?>
    </ul>
</div>
