<?php $block= $block->getLayout()->createBlock('Travers\Feedback\Block\FeedbackForm'); ?>

<div id="feedback_modal" class="feedback_modal" style="display:none;">
    <div class="content">           
        <form class="form contact"
            action="<?php echo $block->getFormAction() ?>"
            id="issue_submit"
            method="post"
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field option required">
                <label class="label" for="option"><span><?= $block->escapeHtml(__('Issue Type')) ?></span></label>
                <div class="control">
                    <select name="option" id="option" title="<?= $block->escapeHtmlAttr(__('Issue Type')) ?>"
                           class="input-text" data-validate="{required:true}">
                            <option value="">Please Select Issue Type...</option>
                            <?php 
                            foreach ($block->getLabelList() as $key => $value):?>
                               <option value="<?= $value ?>" ><?= str_replace("_"," ",$value)?></option>
                            <?php endforeach; ?>
                    </select>

                </div>
            </div>
            <div class="field firstname">
                <label class="label" for="firstname"><span><?= $block->escapeHtml(__('First & Last Name')) ?></span></label>
                <div class="control">
                    <input name="firstname" id="firstname" title="<?= $block->escapeHtmlAttr(__('First & Last Name')) ?>"
                           class="input-text" type="text"/>
                </div>
            </div>
           
            <div class="field emailaddress">
                <label class="label" for="emailaddress"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="emailaddress" id="emailaddress" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text" type="email"/>
                </div>
            </div>
            <div class="field summary required">
                <label class="label" for="summary"><span><?= $block->escapeHtml(__('Issue Summary')) ?></span></label>
                <div class="control">
                    <input name="summary" id="summary" title="<?= $block->escapeHtmlAttr(__('Issue Summary')) ?>"
                           class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field issue_descriptions">
                <label class="label" for="issue_descriptions"><span><?= $block->escapeHtml(__('Issue Description')) ?></span></label>
                <div class="control">
                    <textarea name="issue_descriptions" id="issue_descriptions" title="<?= $block->escapeHtmlAttr(__('Issue Description')) ?>"
                           class="input-text" col="4"></textarea>
                </div>
            </div>
        </fieldset>
        <input type="hidden" value="<?php echo $block->getRequest()->getUriString(); ?>" name="current_url" id="current_url"> 
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" id='issue-submit_button' title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                        class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
    </div>
</div>
<style>
    #issue_submit .actions-toolbar{
        margin-top: 30px
    }
    .feedback_modal .modal-content{
        padding-bottom:0px
    }
    .feedback_modal .modal-inner-wrap{
        padding: 40px 40px !important;
    }
</style>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                title: 'Feedback',
                responsive: true,
                buttons: [],
                modalClass:'feedback_modal',
                clickableOverlay: true
            };

            var popup = modal(options, $('#feedback_modal'));
            $('body').on('click', '.feedback-button', function(e){
                $('#issue_submit').trigger("reset");
                $("#feedback_modal").modal("openModal");
            });

            $('body').on('click', '.feedback_modal', function(e){
                if(jQuery(e.target).closest(".modal-inner-wrap").length == 0){
                    $('#issue_submit').trigger("reset");
                    $("#feedback_modal").modal("closeModal");
                }
            });

            jQuery('body').on('click', '#issue_submit #issue-submit_button', function(e){
                e.preventDefault();
                e.stopImmediatePropagation();
                var dataForm = jQuery('#issue_submit');
                if(dataForm.validation('isValid') === false){
                    return false;
                }
                jQuery.ajax({
                    type: 'post',
                    url: '<?php echo $block->getFormAction() ?>',
                    data: jQuery('#issue_submit').serialize(),
                    cache: false,
                    showLoader: 'true',
                    success: function(data, status, xhr) {
                        $("#feedback_modal").modal("closeModal");
                    },
                    error: function (xhr, status, errorThrown) {
                        $("#feedback_modal").modal("closeModal");
                    }
                });
                return false;
            });

        }
    );
</script>
