<?php $balance = $block->getCustomerBalance(); 
?>
<div class="block block-dashboard-balance">
    <div class="balance-section">
        <div class="block-title">
            <h3><?= __('Account Summary') ?></h3>
        </div>
        <div class="block-content">
            <?php if (isset($balance['FutureBalance'])): ?>
                <p><?= __('Future Balance: ') ?><?= $block->escapeHtml($balance['FutureBalance']) ?></p>
            <?php endif; ?>
            <?php for( $i = 1; $i <= 5; $i++ ): ?>
                <?php if (isset($balance['Total' . $i . 'Text']) && isset($balance['Total' . $i . 'Balance'])): ?>
                    <p><?= $block->escapeHtml($balance['Total' . $i . 'Text']) ?> <?= $block->escapeHtml($balance['Total' . $i . 'Balance']) ?></p>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
    </div>
    <div class="balance-section">
        <div class="block-title">
            <h3><?= __('Period Balance') ?></h3>
        </div>
        <div class="block-content">
            <?php if (isset($balance['FutureBalance'])): ?>
                <p><?= __('Future Balance: ') ?><?= $block->escapeHtml($balance['FutureBalance']) ?></p>
            <?php endif; ?>
            <?php for( $i = 1; $i <= 5; $i++ ): ?>
                <?php if (isset($balance['Period' . $i . 'Date']) && isset($balance['Period' . $i . 'Balance'])): ?>
                    <p><?= $block->escapeHtml($balance['Period' . $i . 'Date']) ?> <?= $block->escapeHtml($balance['Period' . $i . 'Balance']) ?></p>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
    </div>
</div>