<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $viewModel = $block->getViewModel();
    $currentCategory = $viewModel->getCurrentCategory();
    if(($currentCategory->getLevel() > 2 || empty($currentCategory->getChildrenCategories()->getSize())) || !$viewModel->getSubcategoryConfig()) :
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
    <?= $block->getProductListHtml() ?>
<?php 
		endif; 
	endif;
?>
