<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php
$upholsteryBlockId = false;
$stainBlockId = false;
$product = $block->getProduct();

if ($product->getData('upholstery')) {
	$type = $product->getAttributeText('upholstery');
	switch ($type) {
		case "NS":
			$upholsteryBlockId = 'ns_product_block';
			break;
		case "NT":
			$upholsteryBlockId = 'nt_product_block';
			break;
		case "UL Pro":
			$upholsteryBlockId = 'ulpro_product_block';
			break;
	}
}
if ($product->getData('custom_stain')) {
	$stainBlockId = 'stain_product_block';
}
?>

<?php if ($upholsteryBlockId): ?>
	<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($upholsteryBlockId)->toHtml() ?>
<?php endif; ?>

<?php if ($stainBlockId): ?>
	<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($stainBlockId)->toHtml() ?>
<?php endif; ?>
