<div class="color-stains">
	<div class="slogan">
		<h1>Upholstery Options</h1>
	</div>
	<div class="desc">		
		<h3>NaturSoft™ Upholstery</h3>
		<p>At Earthlite, we work hard to provide you with the highest quality, most environmentally friendly materials on the market – this includes our upholstery options. Natursoft™ has a luxurious, silky-smooth feel similar to that of a fine glove leather. We’ve tested Natursoft’s durability with extensive rub tests and it holds up beautifully every time. Natursoft is available in 11 colors.</p>
	     <center>
	     	<img style="width: 85%;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/color_Stain.png'); ?>" alt="">
		</center>
	</div>	
</div>