<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php
$upholsteryBlockId = false;
$stainBlockId = false;
$product = $block->getProduct();

if ($product->getData('upholstery')) {
	$upholsteryBlockId = 'nt_product_block';
	if ($product->getAttributeText('upholstery') == "NS") {
		$upholsteryBlockId = 'ns_product_block';
	}
}
if ($product->getData('custom_stain')) {
	$stainBlockId = 'stain_product_block';
}
?>

<?php if ($upholsteryBlockId): ?>
	<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($upholsteryBlockId)->toHtml() ?>
<?php endif; ?>

<?php if ($stainBlockId): ?>
	<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($stainBlockId)->toHtml() ?>
<?php endif; ?>
