<?php 
	$product = $block->getProduct();	

	$fileAttributes = array('manuals_1', 'manuals_2', 'manuals_3', 'manuals_4', 'manuals_5');	
	
	$fileAttributeValues = array();
	foreach ($fileAttributes as $fileAttribute) 
	{
		if($product->getCustomAttribute($fileAttribute))
		{			
			$fileAttributeUrl = $product->getCustomAttribute($fileAttribute)->getValue();
			if(filter_var($fileAttributeUrl, FILTER_VALIDATE_URL))
			{
				$ext = pathinfo($fileAttributeUrl, PATHINFO_EXTENSION);
				switch (strtolower($ext)) 
				{
	                case 'pdf':
                        $fileAttributeValues[strtolower($ext)] = $fileAttributeUrl;
                        break;
	                case 'doc':
                        $fileAttributeValues[strtolower($ext)] = $fileAttributeUrl;
                        break;
	                case 'xlsx':
                        $fileAttributeValues[strtolower($ext)] = $fileAttributeUrl;
                        break;	                
	         	}			
			}
		}	
	}		
?>
<?php
	if (count($fileAttributeValues)):
?>
	<div class="block download">
		<label> Use Below Links to Download the Specification Sheets</label>
		<div class="block-content">
			<?php
				foreach ($fileAttributeValues as $ext => $attributeUrl) {
			?>
		
			<a href="<?php echo $attributeUrl ?>" class="downloadable-sheet" target="blank" style="display: inline-block; width: 50px">
				<img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/'.$ext.'.png'); ?>" alt="">
			</a>
			<?php } ?>
		</div>
	</div>
<?php else: ?>
	<div class="block download">
		<label> No Specification sheet are provided for this product. </label>		
	</div>
<?php endif; ?>