<?php 
	$product = $block->getProduct();	

	$fileAttributes = array('manuals_1', 'manuals_2', 'manuals_3', 'manuals_4', 'manuals_5');	
	
	$fileAttributeValues = array();
	foreach ($fileAttributes as $fileAttribute) 
	{
		if($product->getCustomAttribute($fileAttribute))
		{			
			$fileAttributeUrl = $product->getCustomAttribute($fileAttribute)->getValue();
			$attributelabel = $block->getAttributeLabel($fileAttribute);
			if(filter_var($fileAttributeUrl, FILTER_VALIDATE_URL))
			{
				$ext = pathinfo($fileAttributeUrl, PATHINFO_EXTENSION);
				switch (strtolower($ext)) 
				{
	                case 'pdf':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileAttributeUrl;
                        break;
	                case 'doc':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileAttributeUrl;
                        break;
	                case 'xlsx':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileAttributeUrl;
                        break;	                
	         	}			
			}
			else {
	            $attributeVal = $product->getCustomAttribute($fileAttribute)->getValue();

				$filePath = $block->getFileUrl($attributeVal);

				$fileMediaPath = $block->getMediaFileUrl($filePath);

				$ext = pathinfo($fileMediaPath, PATHINFO_EXTENSION);
				
				switch (strtolower($ext)) 
				{
	                case 'pdf':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileMediaPath;
                        break;
	                case 'doc':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileMediaPath;
                        break;
	                case 'xlsx':
                        $fileAttributeValues[$attributelabel][strtolower($ext)] = $fileMediaPath;
                        break;	                
	         	}
				
	        }
		}			
	}
?>
<?php
	if (count($fileAttributeValues)):
?>
	<div class="block download">
		<label> Use Below Links to Download the Specification Sheets</label>
		<div class="block-content">
			<table class="data table additional-attributes">
				<tbody>
					<?php
						foreach ($fileAttributeValues as $key => $attributeValue) {
							foreach ($attributeValue as $ext => $attributeUrl) {
					?>
					<tr>
						<th class="col label" scope="row"><?= $key ?></th>
						<td>
							<a href="<?php echo $attributeUrl ?>" class="downloadable-sheet" target="blank" style="display: inline-block; width: 50px">
								<img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/'.$ext.'.png'); ?>" alt="">
							</a>
						</td>
					</tr>
					<?php } } ?>
				</tbody>
			</table>
		</div>
	</div>
<?php else: ?>
	<div class="block download">
		<label> No Specification sheet are provided for this product. </label>		
	</div>
<?php endif; ?>