<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="log-in"  id="popup-modal" style="display:none">
    <div class="sign-in-page">
        <div><h1>Welcome back!</h1></div>
        <div><p>America's Trusted Source of Numismatic Treasures</p></div>
    </div>
    <div class="block block-customer-login">
        <div class="common-form sign-in">
            <div class="login-notify" style="display: none;"></div>
            <div class="block-title main-head text-center">
                <h3>
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Welcome Back!')) ?></strong>
                </h3>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login wpcf7-form"
                      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                      method="post"
                      id="login-form-popup" 
                      autocomplete="off"
                      data-mage-init='{"validation":{}}'
                      onsubmit="return validateform()">
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="field note mb-20 text-center"><?= $block->escapeHtml(__('Sign In to access your account')) ?></div>
                        <div class="field email required mb-20 form-group">
                            <label class="label txt-grey" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control form-control-wrap">
                                <input name="username" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required mb-20 form-group">
                            <label for="pass" class="label txt-grey"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                            <div class="control form-control-wrap">
                                <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <div class="remember">
                            <ul class="list-inline">
                                <li><input  id="boxc" type="checkbox" class="txt-grey">
                                    <label class="cbox1" for="boxc">
                                    <span class="txt-grey"> Remember Me</span>
                            </li>
                                <li class="pull-right">
                                    <div class="secondary">
                                        <a class="action remind" href="javascript:void(0);" id="forget-pwd">
                                            <span><?= $block->escapeHtml(__('Forgot Password?')) ?></span>
                                        </a>
                                    </div>
                                </li>
                            </ul>

                         </div>
                         <div class="g-recaptcha mb-10" data-sitekey="6LdG32wUAAAAAAtB0WR-m6FEH9IPwBcCp6HYECRC"></div>
                         <div class="google-cap" style="display: none">Please validate the captcha</div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="btn button-full action login primary  text-uppercase mb-20" name="send" id="sign_in">
                                    <span><?= $block->escapeHtml(__('Sign In')) ?></span>
                                </button>
                            </div>
                            <div class="new-signup text-center">
                                <p><?= __('New User? ') ?><a href="javascript:void(0);" id="signup-modal"><?= __('Sign Up') ?></a></p>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="social">
            <div class="text-center mb-20">
                <h4>Or Connect Using</h4>
            </div>
            <div class="social-media">
                <ul class="list-inline">
                    <li class="social-links media-first">
                        <a href="#" class="button-social">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_fb.png'); ?>" alt="fb-icon" class="social-icon" />
                            <span class="button-social social-text"><?= __('Facebook') ?></span>
                        </a>
                    </li>
                    <li class=" social-links media-second">
                        <a href="#" class="button-social ">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_google.png'); ?>" alt="google" class="social-icon" />
                            <span class="button-social social-text"><?= __('Google') ?></span>
                        </a>
                   </li>
               </ul>
            </div>
        </div>
    </div>
</div>
      <!-- sign-up page -->
<div class="log-in" id="popup-modal-signup" style="display:none">
    <div class="sign-in-page">
        <div><h1>Welcome to CSN!</h1></div>
        <div><p>America's Trusted Source of Numismatic Treasures</p></div>
    </div>
    <div class="block block-customer-login">
        <div class="common-form sign-up">
            <div class="block-title main-head text-center">
                <h3><strong id="block-customer-login-heading" role="heading" aria-level="2"><?= __("Let's Get Started!") ?></strong></h3>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form create account form-create-account" autocomplete="off" action="<?= $block->getUrl('customer/account/createpost'); ?>" method="post" id="form-validate-popup" data-mage-init='{"validation":{}}' enctype="multipart/form-data" autocomplete="off"
                   onsubmit="return validateform()">
            <fieldset class="fieldset create account" data-hasrequired="<?= __('* Required Fields') ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <div class="field note mb-20 text-center">Sign Up by entering the information below</div>
                <div class="field field-name-fullname required mb-20 form-group">
                    <label class="label txt-grey" for="firstname">
                            <span><?= ('First Name') ?></span>
                    </label>    
                    <div class="control form-control-wrap">
                        <input type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry form-control valid" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>
                <div class="field field-name-fullname required mb-20 form-group">
                    <label class="label txt-grey" for="lastname">
                            <span><?= ('Last Name') ?></span>
                    </label>    
                    <div class="control form-control-wrap">
                        <input type="text" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry form-control valid" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>
                <div class="field email required mb-20 form-group">
                    <label for="email_address" class="label txt-grey" ><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control form-control-wrap">
                        <input type="email" name="email" autocomplete="email" id="email_address" value="" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text required-entry form-control valid" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required mb-20 form-group">
                    <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control form-control-wrap">

                        <input type="password" name="password" id="password-signup" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" class="input-text required-entry form-control valid" autocomplete="off">

                    </div>

                </div>
                <div class="field confirmation required mb-20 form-group">
                    <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                    <div class="control form-control-wrap">
                        <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text required-entry form-control valid" data-validate="{required:true, equalTo:'#password-signup'}" autocomplete="off">
                    </div>
                </div> 
                <div class="remember">
                    <input id="signup-check" type="checkbox" />
                    <label class="cbox1" for="signup-check">
                        <span><?= __('Do you agree to the')?> <a href="/"><?= __('Terms & Conditions') ?></a></span>
                    </label>
                </div>
                <div class="g-recaptcha mb-10" data-sitekey="6LdG32wUAAAAAAtB0WR-m6FEH9IPwBcCp6HYECRC"></div>
                <div class="google-cap" style="display: none">Please validate the captcha</div>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="btn button-full action login primary  text-uppercase mb-20" name="send" id="sign_up"><span>Sign Up</span></button></div>                     
                </div>
                <div class="already-account text-center">
                    <p><?= __('Already have an account? Click') ?><a href="javascript:void(0);" id="login-popup-form"><?= __(' here') ?></a> <?= __('to Sign In.') ?></p>
                </div>
            </fieldset> 
        </form>
    </div>
        </div>
        <div class="social">
            <div class="text-center mb-20">
                <h4>Or Connect Using</h4>
            </div>
            <div class="social-media">
                <ul class="list-inline">
                    <li class="social-links media-first">
                        <a href="#" class="button-social">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_fb.png'); ?>" alt="fb-icon" class="social-icon" />
                            <span class="button-social social-text"><?= __('Facebook') ?></span>
                        </a>
                    </li>
                    <li class=" social-links media-second">
                        <a href="#" class="button-social ">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_google.png'); ?>" alt="google" class="social-icon" />
                            <span class="button-social social-text"><?= __('Google') ?></span>
                        </a>
                   </li>
               </ul>
            </div>
        </div>
    </div>
</div>
<!-- Forget Password -->
<div class="log-in" id="forget-popup" style="display: none;" >
    <div class="sign-in-page">
        <div><h1>We are here to help you!</h1></div>
        <div><p>America's Trusted Source of Numismatic Treasures</p></div>
    </div>
    <div class="block block-customer-login">
        <i class="fa fa-long-arrow-left fa-2x" aria-hidden="true" style="padding: 20px;"></i>
       <div class="common-form forgot-password">
            <div class="block-title main-head text-center mb-20">
                <h3><strong id="block-customer-login-heading" role="heading" aria-level="2"><?= __('Forgot Your Password?') ?></strong></h3>
            </div>
            <div class="block-content">
                <form class="form password forget" autocomplete="off" action="<?= $block->getUrl('customer/account/forgotpasswordpost') ?>" method="post" id="forget-popup" data-mage-init='{"validation":{}}'  onsubmit="return validateform()">
                    <fieldset class="fieldset" data-hasrequired="* Required Fields">
                        <div class="field note text-center mb-20"><?= __('Sign In by entering the information below') ?></div>
                        <div class="field email required mb-20 form-group">
                            <label for="email_forget" class="label txt-grey"><span><?= __('Email') ?></span></label>
                            <div class="control form-control-wrap">
                                <input type="email" name="email" alt="email" id="email_forget" class="input-text form-control" value="" data-validate="{required:true, 'validate-email':true}" aria-required="true">
                            </div>
                        </div>
                            </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="button-full action submit primary text-uppercase"><span>continue</span></button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
require(['jquery','Magento_Ui/js/modal/modal', 'googlecap'],
function($, modal) {
    var options = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        modalClass: 'custom-block-customer-login',
        buttons: false,
    };
    $('#login-popup, #login-popup-form').on("click", function(){
        var popup = modal(options, $('#popup-modal'));
        //$('#popup-modal-signup').modal('closeModal');
        $('#popup-modal').modal('openModal');
    });
    var optsignup = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        modalClass: 'custom-block-customer-signup',
        buttons: false,
    };
    $('#signup-modal').on("click", function(){
        $('#popup-modal').modal('closeModal');
        var popup = modal(optsignup, $('#popup-modal-signup'));
        $('#popup-modal-signup').modal('openModal');
    });
    var optforget = {
        type: 'popup',
        responsive: true,
        innerScroll: true,
        modalClass: 'customer-forgetpassword-popup',
        buttons: false,
    };
    $('#forget-pwd').on("click", function(){
        $('#popup-modal').modal('closeModal');
        var popup = modal(optforget, $('#forget-popup'));
        $('#forget-popup').modal('openModal');
    });
    $('#login-form-popup').on('submit', function (event){
        if($('#login-form-popup').validation('isValid')) {
            event.preventDefault();			
            $.ajax({
                url:'<?= $this->getUrl('ajaxlogin/account/ajaxlogin'); ?>',
                type:'POST',
                showLoader: true,
                dataType:'json',
                data: $('#login-form-popup').serialize(true),								
                success:function(response) { 
                    $('.login-notify').fadeOut().html(response.message).fadeIn(100);
                    if(response.redirectUrl) {
                        setTimeout(function(){											
                            window.location = response.redirectUrl;
                        }, 2000);                            
                    } 
                }
            });
        }
    });
    function validateform() {
        var captcha_response = grecaptcha.getResponse();
        if(captcha_response.length == 0) {        
            return false;
        } else {
            return true;
        }
    }
});
 


    
 </script>