<?php
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="log-in"  id="popup-modal" style="display:none">
    <div class="sign-in-page">
        <div class="heading"><?= $block->escapeHtml(__('Welcome Back!')) ?></div>
        <div><p><?= $block->escapeHtml(__('America\'s Trusted Source of Numismatic Treasures')) ?></p></div>
    </div>
    <div class="block block-customer-login">
        <div class="common-form sign-in">
            <div class="login-notify" style="display: none;"></div>
            <div class="block-title main-head text-center">
                <strong id="block-customer-login-heading" role="heading" aria-level="2">
                    <?= $block->escapeHtml(__('Welcome Back!')) ?>
                </strong>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login wpcf7-form"
                      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                      method="post"
                      id="login-form-popup"
                      autocomplete="off"
                      data-mage-init='{"validation":{}}'
                     >
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="field note mb-20 text-center"><?= $block->escapeHtml(__('Sign In to access your account')) ?></div>
                        <div class="field email required mb-20 form-group">
                            <label class="label txt-grey" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control form-control-wrap">
                                <input name="username" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required mb-20 form-group">
                            <label for="pass" class="label txt-grey"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                            <div class="control form-control-wrap">
                                <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <div class="remember">
                            <ul class="list-inline">
                                <li><input  id="boxc" type="checkbox" class="txt-grey">
                                    <label class="cbox1" for="boxc">
                                    <span class="txt-grey"> Remember Me</span>
                            </li>
                                <li class="pull-right">
                                    <div class="secondary">
                                        <a class="action remind" href="javascript:void(0);" id="forget-pwd">
                                            <span><?= $block->escapeHtml(__('Forgot Password?')) ?></span>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                         </div>

                    <?= $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/gcaptcha.phtml')->setGId('loginGCaptcha')->toHtml(); ?>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="btn button-full action login primary  text-uppercase mb-20" name="send" id="sign_in">
                                    <span><?= $block->escapeHtml(__('Sign In')) ?></span>
                                </button>
                            </div>
                            <div class="new-signup text-center">
                                <p><?= __('New User? ') ?><a href="javascript:void(0);" id="signup-modal"><?= __('Sign Up') ?></a></p>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <div class="social">
            <div class="text-center heading mb-20">
                Or Connect Using
            </div>
            <div class="social-media">
                <?php echo $this->getLayout()->createBlock("Mageplaza\SocialLogin\Block\Popup\Social")->setTemplate("Mageplaza_SocialLogin::form/social.phtml")->toHtml();?>
            </div>
        </div>
    </div>
</div>

<!-- sign-up page -->
<div class="log-in" id="popup-modal-signup" style="display:none">
    <div class="sign-in-page">
        <div class="heading"><?= __("Welcome back!") ?></div>
        <div><p><?= __("America's Trusted Source of Numismatic Treasures") ?></p></div>
    </div>
    <div class="block block-customer-login">
        <div class="common-form sign-up">
            <div class="signup-notify" style="display: none;"></div>
            <div class="block-title main-head text-center">
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= __("Let's Get Started!") ?></strong>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form create account form-create-account" autocomplete="off" method="post" id="signup-popup" data-mage-init='{"validation":{}}' enctype="multipart/form-data" autocomplete="off">
            <fieldset class="fieldset create account" data-hasrequired="<?= __('* Required Fields') ?>">
                <?= $block->getBlockHtml('formkey') ?>
                <div class="field note mb-20 text-center"><?= __('Sign Up by entering the information below') ?></div>
                <div class="field field-name-fullname required mb-20 form-group">
                    <label class="label txt-grey" for="firstname">
                            <span><?= __('First Name') ?></span>
                    </label>    
                    <div class="control form-control-wrap">
                        <input type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry form-control valid" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>
                <div class="field field-name-fullname required mb-20 form-group">
                    <label class="label txt-grey" for="lastname">
                            <span><?= __('Last Name') ?></span>
                    </label>    
                    <div class="control form-control-wrap">
                        <input type="text" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry form-control valid" data-validate="{required:true}" autocomplete="off" aria-required="true">
                    </div>
                </div>
                <div class="field email required mb-20 form-group">
                    <label for="email_address" class="label txt-grey" ><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control form-control-wrap">
                        <input type="email" name="email" autocomplete="email" id="email_address" value="" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text required-entry form-control valid" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required mb-20 form-group">
                    <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control form-control-wrap">
                        <input type="password" name="password" id="password-signup"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               class="input-text required-entry form-control valid"
                               autocomplete="off"
                               data-password-min-length="8"
                               data-password-min-character-sets="3"
                               data-validate="{required:true,'maxlength':20,'validate-customer-password':true}">
                        <div class="strength-meter" id="strength-meter" data-role="password-strength-meter" aria-live="polite">
                            <div  class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span data-role="password-strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field confirmation required mb-20 form-group">
                    <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                    <div class="control form-control-wrap">
                        <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text required-entry form-control valid" data-validate="{required:true, equalTo:'#password-signup'}" autocomplete="off">
                    </div>
                </div> 
                <div class="remember">
                    <input type="checkbox" id="signup-check" data-validate="{required:true}" name="custom-terms" title="<?php /* @escapeNotVerified */ echo __('Terms and contitions') ?>" class="checkbox"  />                    
                    <label class="label cbox1 signupcheck" for="signup-check">
                        <span><?= __('Do you agree to the')?> <a target="_blank" href="<?= $this->getUrl('privacy-policy') ?>"><?= __(' Privacy Policy') ?></a></span>
                    </label>
                </div>

                <br>
                <?= $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/gcaptcha.phtml')->setGId('regGCaptcha')->toHtml(); ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="btn button-full action login primary  text-uppercase mb-20 mt-20" name="send" id="sign_up"><span>Sign Up</span></button></div>                     
                </div>
                <div class="already-account text-center">
                    <p><?= __('Already have an account? Click') ?><a href="javascript:void(0);" id="login-popup-form"><?= __(' here') ?></a> <?= __('to Sign In.') ?></p>
                </div>
            </fieldset> 
        </form>
    </div>
        </div>
        <div class="social">
            <div class="text-center heading mb-20">
                <?= __('Or Connect Using') ?>
            </div>
            <div class="social-media">
               <ul class="list-inline">
                <?php echo $this->getLayout()->createBlock("Mageplaza\SocialLogin\Block\Popup\Social")->setTemplate("Mageplaza_SocialLogin::form/social.phtml")->toHtml();?>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Forget Password -->
<div class="log-in" id="forget-popup" style="display: none;" >
    <div class="sign-in-page">
        <div class="heading"><?= __('We are here to help you!') ?></div>
        <div><p><?= __('America\'s Trusted Source of Numismatic Treasures') ?></p></div>
    </div>
    <div class="block block-customer-login">
        <a href="javascript:void(0);" class="fa fa-long-arrow-left fa-2x bk-to-arw" aria-hidden="true" style="padding: 20px;"></a>
        <div class="common-form forgot-password">
            <div class="forget-notify" style="display: none;"></div>
            <div class="block-title main-head heading text-center mb-20">
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= __('Forgot Your Password?') ?></strong>
            </div>
            <div class="block-content">
                <form class="form password forget" autocomplete="off" method="post" id="forget-password" data-mage-init='{"validation":{}}'>
                    <fieldset class="fieldset" data-hasrequired="* Required Fields">
                        <div class="field note text-center mb-20"><?= __('Sign In by entering the information below') ?></div>
                        <div class="field email required mb-20 form-group">
                            <label for="email_forget" class="label txt-grey"><span><?= __('Email') ?></span></label>
                            <div class="control form-control-wrap">
                                <input type="email" name="email" alt="email" id="email_forget" class="input-text form-control" value="" data-validate="{required:true, 'validate-email':true}" aria-required="true">
                            </div>
                        </div>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="button-full action submit primary text-uppercase"><span><?= __('continue') ?></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Password confirmation -->
<div class="log-in"  id="confirm-popup" style="display:none">
    <div class="sign-in-page">
        <div class="heading"><?= $block->escapeHtmlAttr(__('Welcome back!')) ?></div>
        <div><p><?= $block->escapeHtmlAttr(__('America\'s Trusted Source of Numismatic Treasures')) ?></p></div>
    </div>
    <div class="block block-customer-login">
    <a href="javascript:void(0);" class="fa fa-long-arrow-left fa-2x bk-to-arw" aria-hidden="true" style="padding: 20px;"></a>
        <div class="common-form sign-in">
            <div class="confirm-notify" style="display: none;"></div>
           
            <div class="block-title main-head text-center">
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Welcome Back!')) ?></strong>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
               <form action="" method="post" id="confirm-popup-form" class="form form-login wpcf7-form form send confirmation" data-mage-init='{"validation":{}}'>
                    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <p class="field note"><?= $block->escapeHtml(__('Please enter your email below and we will send you the confirmation link.')) ?></p>
                        <div class="field email required">
                            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input type="email" name="email" id="email_address_confirm" class="input-text" value="" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="btn button-full action send primary text-uppercase"><span><?= $block->escapeHtml(__('Send confirmation link')) ?></span></button>
                        </div>
                        <div class="secondary">
                            <a href="javascript:void(0);" class="action back"><span><?= $block->escapeHtml(__('Back to Sign In')) ?></span></a>;
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="social">
            <div class="text-center heading mb-20">
                <?= $block->escapeHtml(__('Or Connect Using')) ?>
            </div>
            <div class="social-media">
                <ul class="list-inline">
                <?php echo $this->getLayout()->createBlock("Mageplaza\SocialLogin\Block\Popup\Social")->setTemplate("Mageplaza_SocialLogin::form/social.phtml")->toHtml();?>
                </ul>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Theme/js/authentication": {
                "ajaxLoginUrl": "<?= $this->getUrl('ajaxlogin/account/ajaxlogin', ['isAjax' => true]) ?>",
                "ajaxRegisterUrl": "<?= $this->getUrl('ajaxlogin/account/ajaxregister', ['isAjax' => true]) ?>",
                "ajaxForgetPasswordUrl": "<?= $this->getUrl('ajaxlogin/popup/forgot') ?>",
                "ajaxReconfirmUrl": "<?= $this->getUrl('ajaxlogin/account/confirmation') ?>",
                "accountUrl": "<?= $this->getUrl('customer/account') ?>"
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>