<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="new-signup text-center">
        <p>
    <?= __('Don\'t have an account?')?> <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>"><?= __('Sign Up') ?></a>
        </p>
    </div>
</div>
<?php endif; ?>
