<?php
    $viewModel = $block->getViewModel();
    $category = $viewModel->getCurrentCategory();
    $categoryUrl = $category->getUrl();
    $brands = $viewModel->getBrands();
?>
<div class="shop-by-brand gutter">
    <h2 class="text-center mb-6">Shop By Brand</h2>
    <div class="sbb-slider outer-arrow">
        <?php foreach ($brands as $brand ):?>
        <a class="item" href="<?=$categoryUrl?>?brands=<?=$brand['brandValue']?>"><figure><img src="<?=$brand['brandImage'] ?>" alt="<?=$brand['brandLabel'] ?>" /></figure></a>
        <?php endforeach; ?>
    </div>
</div>

<script>
    require(['jquery', 'slick'], function ($) {
        "use strict";
        $(function () {
            let $brandSlider = $('.sbb-slider');
            $brandSlider.slick({
                infinite: false,
                speed: 300,
                slidesToShow: 3,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 992,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 400,
                        settings: {
                            arrows: false,
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }

                ]
            });
        });
    });
</script>
