<?php
/**
 * Catalog Media slider template
 *
 * @var $block \Earthlite\Category\Block\Category\View
 */
$catalogProductUrl = $block->getMediaUrl() . 'catalog/product';
$categoryGalleryImages = $block->getImages();
$categoryName = $block->getCurrentCategory()->getName();
?>

<div class="gallery-container">
    <div class="category-image">
        <?php foreach ($categoryGalleryImages as $categoryGalleryImage): ?>
            <div>
                <img src="<?= $catalogProductUrl . $categoryGalleryImage->getValue() ?>" 
                     alt="<?= $categoryGalleryImage->getLabel() ?? $categoryName ?>"/>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="" >
    <h2><?= $categoryName ?> </h2>
    <?php if ($_description = $block->getCurrentCategory()->getDescription()) : ?>
        <div class="category-description">
            <?=
            /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                    $block->getCurrentCategory(), $_description, 'description'
            )
            ?>
        </div>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
{
   "*": {
       "Earthlite_Category/js/category-image-slider":{}
   }
}
</script>
