<?php
/**
 * Catalog Media slider template
 *
 * @var $block \Earthlite\Category\Block\Category\View
 */
$catalogProductUrl = $block->getMediaUrl() . 'catalog/product';
$categoryGalleryImages = $block->getImages();
$categoryName = $block->getCurrentCategory()->getName();
$catalogCategoryDefaultUrl = $block->getMediaUrl() . 'catalog/category/placeholder/';
?>

<div class="clp-banner">
    <?php if ($categoryGalleryImages->getSize()>0) { ?>
        <?php foreach ($categoryGalleryImages as $categoryGalleryImage): ?>
            <div class="bg-img slide">
              <img src="<?= $catalogProductUrl . $categoryGalleryImage->getValue() ?>" alt="<?= $block->escapeHtmlAttr($categoryGalleryImage->getLabel()??$categoryName) ?>" title="" class="image" />
            </div>
        <?php endforeach; ?>
    <?php } else { ?>
        <div class="bg-img slide" >
              <img src="<?= $catalogCategoryDefaultUrl . $block->getDefaultCategoryImage() ?>" alt="category" title="" class="image" />
        </div>
    <?php } ?>
</div>

<div class="container clpdesc">
    <div class="clp-titledesc">
        <h2 class="text-center" ><?= $categoryName ?> </h2>
        <?php if ($_description = $block->getCurrentCategory()->getDescription()) : ?>
            <div class="category-description" >
                <?=
                /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                        $block->getCurrentCategory(), $_description, 'description'
                )
                ?>
            </div>
        <?php endif; ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "*": {
    "Earthlite_Category/js/category-image-slider":{}
    }
    }
</script>
