<a rel="nofollow" onclick="javascript:void(0);" id="backtotop">
    <span class="gt-arrow">^</span>
    <div class="d-md-none">
        <span class="icon-arrow-right"></span>
        <span class="text"><?= $block->escapeHtml(__('Back To Top')) ?></span>
    </div>
</a>

<script type="text/javascript">
 require(['jquery', 'domReady!'], function($){
 var $bt = $('#backtotop');
 function ManageGoToTop() {
         if($(this).scrollTop() > 300) {
             $bt.fadeIn();
         } else {
             $bt.fadeOut();
         }
     }
     ManageGoToTop();
     $(window).scroll(ManageGoToTop);
     $bt.on('click touch',function() {
         $('body,html').animate({scrollTop:0},500);
 return false;
     })
});
</script>