<?php
	$_helper = $this->helper('Earthlite\Stickylinks\Helper\StoreConfig');
	$storeContactNumber = $_helper->getConfigValue('general/store_information/phone');
	if($storeContactNumber):
?>

<a class="sticky contact hidden-print" href="<?php echo "tel:".str_replace("-","",$storeContactNumber) ?>">
       <div class="tooltip-toggle">
        <i class="icon-phone"></i>
	<!--<span>Contact</span>-->
       </div>
        <div class="tooltip-content d-none d-md-block"><?php echo $storeContactNumber ?></div>
</a>

<?php endif; ?>