<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Earthlite\InfiniteScroll\Block\Init $block */
?>

<?php if ($block->isEnabled()) : ?>
    <?php
    $productListMode = $block->getProductListMode();
    $mode = ($productListMode == 'grid') ? $block->getSelector('items_grid') : $block->getSelector('items_list');
    ?>
    <script id="infinite-scroller">
        window.iasConfig = {
            mode: '<?php echo $block->escapeHtml($mode); ?>',
            debug: <?php echo (int) $block->getScrollConfig('general/debug'); ?>,
            container: '<?php echo $block->escapeHtml($block->getSelector('content')); ?>',
            next: '<?php echo $block->escapeHtml($block->getSelector('next')); ?>',
            pagination: '<?php echo $block->escapeHtml($block->getSelector('pagination')); ?>',
            buffer: <?php echo (int) $block->getDesign('buffer_px'); ?>,
            prev: '<?php echo $block->escapeHtml($block->getSelector('previous')); ?>',
            text: '<?php echo $block->escapeJsQuote(__($block->getDesign('done_text'))); ?>',
            html: '<div class="ias-noneleft" style="text-align: center;">{text}</div>',
            spinnerSrc: '<?php echo $this->getViewFileUrl('Earthlite_InfiniteScroll::images/loading-gear.gif'); ?>',            
            spinnerHtml: '<?php echo '<div class="ias-spinner w-100 text-center" ><img style="display:inline" src="{src}"/> '.
                $block->escapeJsQuote(__($block->getScrollConfig('design/loading_text'))).
                '</div>'; ?>',
            trigger: {
                text: '<?php echo $block->escapeJsQuote(__($block->getDesign('load_more_text'))); ?>',
                html: '<div class="ias-trigger ias-trigger-next" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                textPrev: '<?php echo $block->escapeJsQuote(__($block->getDesign('load_more_text_prev'))); ?>',
                htmlPrev: '<div class="ias-trigger ias-trigger-prev" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                offset: <?php echo (int) $block->getDesign('load_more_threshold'); ?>
            },
            toolbarSelector: '<?php echo $block->escapeHtml($block->getSelector('toolbar')); ?>',
            toolbarAction: '<?php echo $block->getDesign('hide_toolbar') ? 'hide' : 'show'; ?>',
            memoryActive: <?php echo $block->isMemoryActive() ? 'true' : 'false'; ?>
        };
        require(['jquery', 'infinitescroll'], function($){
            $(function($) {
                // InfiniteScroll:
                CustomIAScroll.init();
            });
        });
    </script>
<?php endif ?>
