<?php

 /** @var \Ziffity\AjaxLogin\Block\Form\ForgotPassword $block */

if (!$block->customerIsAlreadyLoggedIn()): ?>
<div id="customer-popup-forgot" class="customer-popup-forgot">
    <div class="block block-customer-forgot">
        <div class="block-content" aria-labelledby="block-customer-popup-login-heading">
            <form class="form-forgot"
                      action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                      method="post"
                      id="customer-popup-forgot-form"
                      data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>
                <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                    <div class="messages"></div>
                    <div class="field email required">
                        <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action signin-link" href="javascript:void(0);"><span><?= $block->escapeHtml(__('Back to Login')) ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
            {
                "#customer-popup-forgot": {
                    "Ziffity_AjaxLogin/js/action/customer-authentication-popup": {
                        "popupTitle": "<?php /* @escapeNotVerified */ echo __('Forgot Your Password ?'); ?>",
                        "innerWidth": "600"
                    }
                }
            }
        </script>
</div>
<?php endif; 