<?php

 /** @var \Ziffity\AjaxLogin\Block\Form\Login $block */

if (!$block->getHelper()->customerIsAlreadyLoggedIn()): ?>
    <div id="customer-popup-login" class="customer-popup-login">
        <div class="block block-customer-login">
            <div class="block-content" aria-labelledby="block-customer-popup-login-heading">
                <form class="form form-login"
                      action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                      method="post"
                      id="customer-popup-login-form"
                      data-mage-init='{"validation":{}}'>
                    <?php echo $block->getBlockHtml('formkey'); ?>
                    <input type="hidden" name="redirect_url" id="redirect-url" value="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
                    <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                        <div class="messages"></div>
                        <div class="field email required">
                            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                            <div class="control">
                                <input name="username" value="" <?php if ($block->getHelper()->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email-login" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                            <div class="control">
                                <input name="password" type="password" <?php if ($block->getHelper()->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass-login" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}" >
                            </div>
                        </div>

                        <div class="actions-toolbar">
                            <div class="secondary">
                                <div class="field choice">
                                    <input type="checkbox" class="checkbox" id="remind-me">
                                    <label class="label" for="remind-me">Keep me logged in</label>
                                </div>
                                <a id="customer-forgot-popup" class="action remind" href="javascript:void(0);">
                                    <span>Forgot Password?</span>
                                </a>

                            </div>
                            <div class="primary"><button type="submit" class="action login primary" name="send" id="send2-login"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>



                        </div>
                        <?php if ($block->getHelper()->getRegistration()->isAllowed()): ?>
                            <div class="create-ac">Don't have an account? <a class="action create" href="javascript:void(0);" id="customer-popup-registration"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
                            </div>
                        <?php endif; ?>
                    </fieldset>
                </form>
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#customer-popup-login": {
                    "Ziffity_AjaxLogin/js/action/customer-authentication-popup": {
                        "popupTitle": "<?php /* @escapeNotVerified */ echo __('Sign In') ?>",
                        "innerWidth": "400"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
