<?php
/**
 * Copyright © 2018 Vantiv, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var Vantiv\Payment\Block\Adminhtml\System\Config\ImportCodes $block
 */
?>
<div class="fieldset admin__field">
    <div class="admin__field-control">
        <input type="file" id="import_codes_file" name="import_codes_file" class="input-file"/>
        <button class="scalable" type="button" id="<?php echo $block->getImportButtonId(); ?>">
            <span><span><span><?php echo $block->escapeHtml(__('Import Gift Card Codes')); ?></span></span></span>
        </button>
    </div>
</div>

<script type="text/x-magento-init"><?php echo $block->getMageInitJson();?></script>
