<?php

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
/**
 * Product list template
 *
 * @var $block \Ziffity\Filteredproducts\Block\CustomerWhoBought
 */
$viewMode = 'grid';
$image = 'category_page_grid';
$pos = $block->getPositioned();
$i = 1;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

/*load best seller if no combination*/
if(!$_productCollection->count()){
  $_productCollection = $this->getLayout()->createBlock('Ziffity\Filteredproducts\Block\Bestseller')->getProducts();
}

if ($_productCollection->count()): ?>
<div class="product-widget__inner br whitesmoke" style="margin-top:30px;">
    <div class="heading-sec clearfix">
        <h2 class="pull-left"><?= __('People who bought this item also bought') ?></h2>
    </div>

    <div class="block widget block-products-list grid">
        <div class="block-content">
            <!-- new_products_content_widget_grid-->
            <div class="products-grid grid">
                <ol class="products list items product-items clearfix">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php $iterator = 1; ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php
                    /*call for price */
                    $callforprice = false;
                    $callforClass = '';
                    /*to check call for price */
                    $callForAttr = $_product->getResource()->getAttribute('callforquote');
                    if($callForAttr){
                        $val = $callForAttr->getFrontend()->getValue($_product)->getText();
                        if($val == 'Yes'){
                            $callforprice = true;
                            $callforClass = 'callforprice-product';
                        }
                    }
                    ?>
                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item '.$callforClass.' col-xs-6 col-sm-6 col-md-3 col-lg-20">' : '</li><li class="item product product-item '.$callforClass.' col-xs-6 col-sm-6 col-md-3 col-lg-20">' ?>

                    <div class="product-item-info" data-container="product-grid">
                    <?php
                        /*ziffity special price sale badge*/
                        $specialprice = $_product->getSpecialPrice();
                        $specialPriceFromDate = $_product->getSpecialFromDate();
                        $specialPriceToDate = $_product->getSpecialToDate();
                        $today =  time();
                         if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate)
                                && $today <= strtotime($specialPriceToDate)
                                || $today >= strtotime( $specialPriceFromDate)
                                && is_null($specialPriceToDate)
                            ){
                        ?>
                        <div class="product-label"><span class="sale-product-icon">Sale</span></div>
                        <?php
                            }
                        }
                    ?>
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                       <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?php if(!$callforprice){ ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?php } ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <a class="weltpixel-quickview weltpixel_quickview_button_v2 action quick-view" data-quickview-url="<?php echo $this->getUrl() ?>weltpixel_quickview/catalog_product/view/id/<?php echo $_product->getId();?>" href="javascript:void(0);">
                                                <span><?php echo __('Quick View') ?></span>
                                            </a>
                                            <?php  if($callforprice) : ?>
                                            <button class="btn-callforprice action">
                                                <span><?= /* @escapeNotVerified */ __('Call For Price') ?></span>
                                            </button>
                                        <?php
                                        else: ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php if($_product->getTypeId() == 'configurable'): ?>
                                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"
                                                            title="<?= $block->escapeHtml(__('View Details')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('View Details') ?></span>
                                                    </a>
                                            <?php else: ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product) ?>'
                                               class="action towishlist" data-action="add-to-wishlist"
                                               title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>"
                                               data-action="add-to-wishlist"
                                               role="button"
                                               aria-label="Add to Wish List">  
                                                    <i class="fa fa-heart-o"></i>
                                                    <span class="sr-only"><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if ($i++ == 5) break; ?>
                <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
   {
       "[data-role=tocart-form], .form.map.checkout": {
           "catalogAddToCart": {
               "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
           }
       }
   }
</script>
<?php endif; ?>