<?php
/** @var \Earthlite\NewTrending\Block\Category\NewTrendingList $block */
$newTrendingProducts = $block->getNewTrendingList();
?>
<?php if ($exist = ($block->getNewTrendingList() && $block->getNewTrendingList()->getSize())) : ?>
    <section class="new-trend-wrap inner-container">
    <h2 class="mb-6 text-center" data-aos="fade-up"><?= $block->escapeHtml($block->getData('title')) ?></h2>
    <div class="wrapper grid products-grid new-trend-products" >
    <ol class="new-trend-slider product-items">
        <?php
        foreach ($newTrendingProducts as $newTrendingProduct) {
            $productDetails = $block->getProductDetails($newTrendingProduct->getId());
            ?>
            <li class="item product product-item">

                <div class="product-item-info">
                    <a href="<?= $newTrendingProduct->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img class="product-image-photo" src="<?= $block->getImageUrl($newTrendingProduct->getThumbnail()); ?>" max-width="240" max-height="300" alt="<?= $productDetails->getName(); ?>">
                            </span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $newTrendingProduct->getProductUrl(); ?>"><?= $productDetails->getName(); ?></a>
                        </strong>
                        <div class="price-box">
                            <span class="price"><?= $block->getProductPrice($newTrendingProduct); ?> </span>
                        </div>

                        <div class="product-item-inner">
                            <div class="product-item-actions">
                                <div class="actions-primary">
                                    <a href="<?= $newTrendingProduct->getProductUrl(); ?>" class="action primary"><?= $block->escapeHtml(__('View Details')) ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php } ?>
    </ol>
    </div>
    </section>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "Earthlite_NewTrending/js/newtrendslider":{}
    }
}
</script>