<?php
/**
 * @var $block Earthlite\Instagram\Block\Widget
 */
?>
<?php if($block->isEnabled()) : ?>
    <?php if($block->getTemplateType() == 'slick'): ?>
        <div data-bind="scope: 'instaFeed'">
            <section class="home-instagram">
                <div class="inner-container">
                    <h2 data-aos="fade-up"><?= $block->getHeadingTitle() ?></h2>
                    <a href="<?= $block->getInstagramCmsUrl() ?>" class="action primary mb-4 mb-md-5" target="_blank" data-aos="fade-up">
                        <?= $block->escapeHtml(__('@earthlite_massage'))?>
                    </a>
                    <div class="position-relative" data-aos="fade-up">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </div>
            </section>
        </div>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "instaFeed": {
                            "component" : "Earthlite_Instagram/js/instagram",
                            "template" : "Earthlite_Instagram/feed",
                            "access_token" : "<?= $block->getAccessToken() ?>",
                            "api_endpoint" : "<?= $block->getApiEndpoint() ?>",
                            "limit" : "<?= $block->getPostCount() ?>",
                            "slick" : true
                        }
                    }
                }
            }
        }
        </script>
    <?php else: ?>
        <div data-bind="scope: 'instaFeed'">
            <section class="cms-instagram">
                <div class="inner-container">
                    <h2 class="mb-6 mt-3 mt-md-5 text-center"><?= $block->getHeadingTitle() ?></h2>
                    <div class="position-relative" >
                    <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </div>
            </section>
        </div>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "instaFeed": {
                            "component" : "Earthlite_Instagram/js/instagram",
                            "template" : "Earthlite_Instagram/feed",
                            "access_token" : "<?= $block->getAccessToken() ?>",
                            "api_endpoint" : "<?= $block->getApiEndpoint() ?>",
                            "limit" : "<?= $block->getPostCount() ?>",
                            "slick" : false
                        }
                    }
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
