<?php
/**
 * @var $block Earthlite\Instagram\Block\Widget
 */
?>
<?php if($block->isEnabled()) : ?>
    <div data-bind="scope: 'instaFeed'">
        <section class="home-instagram mb-10">
            <div class="inner-container">
                <h2 class="mb-6" data-aos="fade-up"><?= $block->escapeHtml(__('Meet The Community')) ?></h2>
                <div class="position-relative" data-aos="fade-up">
                <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
        </section>
    </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "instaFeed": {
                        "component" : "Earthlite_Instagram/js/instagram",
                        "template" : "Earthlite_Instagram/feed",
                        "access_token" : "<?= $block->getAccessToken() ?>",
                        "api_endpoint" : "<?= $block->getApiEndpoint() ?>"
                    }
                }
            }
        }
    }
    </script>
<?php endif; ?>
