<?php

/** @type \Earthlite\LayerNavigation\Model\Layer\Filter\Attribute $filter */
$filter = $this->getFilter();

$attributeCode = $filter->getRequestVar();

/** @type \Earthlite\LayerNavigation\Model\Layer\Filter $filterModel */
$filterModel = $this->helper(\Earthlite\LayerNavigation\Helper\Data::class)->getFilterModel();

?>
<ol class="items">
    <?php 
        foreach ($filterItems as $filterItem) : ?>
            <li class="item">
                <?php if ($filterModel->isSliderTypes($filter)) : ?>
                    <div id="ln_slider_container_<?= /** @noEscape */ $attributeCode ?>" class="ln_slider_container">
                        <div id="custom_slider_<?= /** @noEscape */ $attributeCode ?>"></div>
                        <div id="custom_price_text"></div>
                    </div>
                <?php break; else : ?>
                    <?php if ($filterItem->getCount() > 0) : ?>
                        <input type="<?= /** @noEscape */ $filterModel->isMultiple($filter) ? 'checkbox' : 'radio' ?>"
                            <?= /** @noEscape */ $filterModel->isMultiple($filter) ? '' : 'name="' . $filter->getRequestVar() . '"' ?>
                            <?= /** @noEscape */ $filterModel->isSelected($filterItem) ? 'checked="checked"' : '' ?> />
                    <?php else : ?>
                        <input type="<?= /** @noEscape */ $filterModel->isMultiple($filter) ? 'checkbox' : 'radio' ?>"
                               disabled="disabled"/>
                    <?php endif; ?>
                    <a href="<?= /** @noEscape */ $block->escapeUrl($filterModel->getItemUrl($filterItem)) ?>">
                        <?= /** @noEscape */ $filterItem->getLabel() ?>
                        <?php if ($filterModel->isShowCounter($filter)) : ?>
                            <span class="count"><?= /** @noEscape */ $filterItem->getCount() ?>
                                <span class="filter-count-label">
                                    <?= /** @noEscape */ ($filterItem->getCount() === 1) ? 'item' : 'items' ?>
                                </span>
                            </span>
                        <?php endif; ?>
                    </a>
                <?php endif; ?>
            </li>
    <?php endforeach ?>
</ol>
