<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */
?>

<?php 
    $websites = $block->getWebsites();
    $currentWebsiteId = $block->getCurrentWebsiteId();
?>

<div class="switcher store switcher-store" id="switcher-store">
    <div class="actions dropdown options switcher-options">
        <?php foreach ($websites as $website): ?>
        <?php if ($currentWebsiteId == $website->getId()): ?>
            <div class="action toggle switcher-trigger"
                 role="button"
                 tabindex="0"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true"
                 id="switcher-store-trigger">
                <strong>
                    <span><?php echo $block->escapeHtml($website->getName()) ?></span>
                </strong>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($websites as $website): ?>
            <?php if (!($currentWebsiteId == $website->getId())): ?>
                <li class="switcher-option">
                    <a href='<?php echo $website->getDefaultStore()->getCurrentUrl() ?>'>
                        <?php echo $block->escapeHtml($website->getName()) ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
