<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type='button' value='-' class='qtyminus' field='qty' />
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
                <input type='button' value='+' class='qtyplus' field='qty' />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script type="text/javascript">
    require(['jquery'], function ($) {
        setTimeout(function () {
            $('.input-text.qty').on('blur keydown keypress keyup', function(e){
                if($(this).val().match(/^0/)){
                    $(this).val(1);
                    return false;
                }

                if($(this).val() == '') {
                    $(this).val(1);
                    return false;
                }
            });
            $('.field.qty .qtyplus').click(function (e) {                    
                e.preventDefault();
                fieldName = $(this).attr('field');
                var currentVal = parseInt($('#'+fieldName).val());
                if (!isNaN(currentVal)) {
                    $('#'+fieldName).val(currentVal + 1);
                } else {                        
                    $('#'+fieldName).val(1);
                }
            });
            $(".field.qty .qtyminus").click(function (e) {                    
                e.preventDefault();
                fieldName = $(this).attr('field');
                var currentVal = parseInt($('#'+fieldName).val());
                if (!isNaN(currentVal) && currentVal > 1) {
                    $('#'+fieldName).val(currentVal - 1);
                }
            });
        }, 100);
    });        
</script>