<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

<?php $title = __('Read More');?>

<script type="text/javascript">
        require(['jquery', 'matchMedia', 'tabs'], function($, mediaCheck) {

            if($('.product.data.items > .item.title').length > 4) {
                $('.product.info.detailed').addClass('tab-size');
            }

            var detailsTabs = $('.product.data.items');
            var readMore = '<a href="#description" class="action more"><?= $title ?></a>';

            $(readMore).appendTo('.product.attribute.overview');

            $('.product-info-main .product.attribute.overview a').click(function (event) {
                var anchor,
                header = $('.header-wrapper').outerHeight();
                event.preventDefault();
                anchor = $(this).attr('href').replace(/^.*?(#|$)/, '');
                $('.product.data.items [data-role="content"]').each(function (index) { //eslint-disable-line
                    if (this.id == 'description') { //eslint-disable-line eqeqeq
                        detailsTabs.tabs('activate', index);
                        $('html, body').animate({
                            scrollTop: $('.product-tab-wrapper').offset().top - header
                        }, 300);
                    }
                });
            });

            $(window).resize(function(){
                if($(window).width() >= 768) {
                    detailsTabs.tabs('activate', 0);
                }
            })

            mediaCheck({
                media: '(min-width: 768px)',
                // Switch to Desktop Version
                entry: function () {
                    detailsTabs.tabs({
                        openedState: "active",
                        collapsible: false,
                        active: 0
                    });
                },
                // Switch to Mobile Version
                exit: function () {
                    detailsTabs.tabs({
                        openedState: "active",
                        collapsible: true,
                        active: 0
                    });
                }
            });
        })
</script>
