<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-header clearfix">
           
            <?php echo $this->getInfoHtml() ?>
        </div>

        <div class="post-content">
            <div class="post-description clearfix">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <img class="img-responsive" src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </div>
                <?php } ?>
                <div class="post-text-hld">
                    <?php $content = preg_replace("/<img[^>]+\>/i", "", $block->getContent(), 1); ?>
                    <?php echo $content; ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

      
    </div>

</div>
<?php echo $this->getChildHtml('blog.post.categories.custom') ?>
<?php echo $this->getChildHtml('blog.post.comments') ?>
<div class="post-bottom">
 <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
<div class="subscribe-sec">
            <button id="blog-subscribe" data-url="http://shopcsntv.com/blogsubscribe" class="action btn-subscribe" title="Subscribe to our Blog"><span><span>Subscribe to our Blog</span></span></button>
                </div>
        </div>