<?php
/**
 * Copyright © 2018 Vantiv, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */
$details = $block->getData('details');
$icon = $block->getData('icons')[$details['ccType']];
$id = $block->escapeHtml($block->getData('id'));
?>
<div data-mage-init='{
        "Vantiv_Payment/js/vault": {
            "container": "payment_<?php echo $id; ?>",
            "publicHash": "<?php echo $block->escapeHtml(
                                $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH)
                            ); ?>",
            "code": "<?php echo $block->escapeHtml($block->getData('code')); ?>"
        }
    }' id="payment_<?php echo $id;?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?php echo $id; ?>" name="payment[token_switcher]"/>
        <img src="<?php echo $block->escapeUrl($icon['url']); ?>"
             width="<?php echo $block->escapeHtml($icon['width']); ?>"
             height="<?php echo $block->escapeHtml($icon['height']); ?>"
             class="payment-icon">
        <span><?php echo $block->escapeHtml(__('ending'));?></span>
        <span><?php echo $block->escapeHtml($details['ccLast4']); ?></span>
        (<span><?php echo $block->escapeHtml(__('expires'));?></span>:
        <span><?php echo $block->escapeHtml(
                $details['ccExpMonth'] . '/' . $details['ccExpYear']
            ); ?></span>)
    </div>
</div>
