<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title><?php echo $this->pageTitle?></title>
    <base href="<?php echo $this->getViewFileUrl()?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <main class="page-main">
        <img src="images/sd-shop.png" title="SD Shop" class="logo">
        <?php require_once $contentTemplate; ?>
        <ul class="social-nav">
            <li>
                <a href="https://www.instagram.com/somethingdigitl" target="_blank" rel="noopener noreferrer">
                    <img src="images/social_instagram.svg" alt="Instagram">
                </a>
            </li>

            <li>
                <a href="https://www.facebook.com/somethingdigitl" target="_blank" rel="noopener noreferrer">
                    <img src="images/social_facebook.svg" alt="Facebook">
                </a>
            </li>

            <li>
                <a href="#" target="_blank" rel="noopener noreferrer">
                    <img src="images/social_pinterest.svg" alt="Pinterest">
                </a>
            </li>

            <li>
                <a href="https://www.twitter.com/somethingdigitl" target="_blank" rel="noopener noreferrer">
                    <img src="images/social_twitter.svg" alt="Twitter">
                </a>
            </li>

            <li>
                <a href="Google PLus" target="_blank" rel="noopener noreferrer">
                    <img src="images/social_google.svg" alt="Google+">
                </a>
            </li>
        </ul>
    </main>
</body>
</html>
