<?php
/**
 * Copyright © 2018 Vantiv, LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */
use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var \Vantiv\Payment\Block\Vault\EcheckRenderer $block */
?>
<tr>
    <td data-th="<?php echo $block->escapeHtml(__('Account Number')); ?>" class="col echeck-account-number">
        <span><?php echo $block->escapeHtml(__('ending')); ?></span>
        <?php echo $block->escapeHtml($block->getAccountNumber()); ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Routing Number')) ?>" class="col echeck-routing-number">
        <?php echo $block->escapeHtml($block->getRoutingNumber()); ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Account Type')); ?>" class="col echeck-account-tpe">
        <?php echo $block->escapeHtml($block->getAccountType()); ?>
    </td>
    <td data-th="<?php echo $block->escapeHtml(__('Actions')); ?>" class="col actions">
        <form
            class="form"
            style="display: inline;"
            action="<?php echo $block->escapeUrl($block->getUrl('vault/cards/deleteaction')); ?>"
            method="post"
        >
            <?php echo $block->getBlockHtml('formkey')?>
            <input
                name="<?php echo $block->escapeHtml(PaymentTokenInterface::PUBLIC_HASH); ?>"
                value="<?php echo $block->escapeHtml($block->getToken()->getPublicHash()); ?>"
                type="hidden"
            />
            <button
                type="submit"
                class="action delete"
                data-mage-init='{
                    "Magento_Vault/js/customer_account/deleteWidget":{
                        "type": "popup",
                        "modalClass": "my-credit-cards-popup",
                        "toggleEvent": "click",
                        "title": "<?php echo $block->escapeHtml(__('Delete')); ?>",
                        "content": "Are you sure you want to delete this account: <?php echo $block->escapeHtml($block->getAccountNumber()); ?>?"
                    }
                }'
            >
                <span><?php echo $block->escapeHtml(__('Delete')); ?></span>
            </button>
        </form>
    </td>
</tr>
