<?php
// @codingStandardsIgnoreFile

/** @var \Ziffity\Webforms\Block\Main $block */
?>
<form class="form form-login wpcf7-form" id="customer-comments-form" method="post" autocomplete="off" action="<?php echo $this->getUrl("webforms/index/post")?>">
   <?= $block->getBlockHtml('formkey') ?>   
   <fieldset class="fieldset login" data-hasrequired="* Required Fields">

        <div class="field field-name-fullname required mb-20 form-group">
            <label class="label txt-grey" for="fullname"> <span>Full Name</span> </label>
            <div class="control wpcf7-form-control-wrap">                
                <input id="cust_name" class="input-text required-entry form-control valid" title="Full Name" autocomplete="off" name="cust_name" type="text" value="" data-validate="{required:true}" />                
                <div class="mage-error"></div>
            </div>
        </div>
        <div class="field email required mb-20 form-group">
            <label class="label txt-grey" for="email"><span>E-mail</span></label>
            <div class="control wpcf7-form-control-wrap">
                <input id="cust_email" class="input-text form-control valid" title="E-mail" autocomplete="off" name="cust_email" type="email" value="" data-validate="{required:true, 'validate-email':true}" />
                <div class="mage-error"></div>
            </div>
        </div>
        <div class="field phone required mb-20 form-group">
            <label class="label txt-grey" for="pass"><span class="mb-10">Phone</span></label>
            <div class="control wpcf7-form-control-wrap">
                <input id="cust_phone" class="input-text form-control valid" title="Phone" autocomplete="off" name="cust_phone" type="text" data-validate="{required:true,'ph_no_validation':true}" />
            </div>
        </div>      
        <div class="field message required mb-20 form-group">
            <label class="label txt-grey" for="message"><span>Message</span></label>
            <div class="control wpcf7-form-control-wrap">
                <input class="input-text form-control" title="Message" autocomplete="off" name="cust_comments" id="cust_comments" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <input type="text" name="form_type" id="form_type" value="contact" class="hidden input-text" data-validate="{required:true}">
        <div class="field required">
            <?= $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/gcaptcha.phtml')->setGId('contactGCaptcha')->toHtml(); ?>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button id="send2" class="btn button-full action login primary text-uppercase mb-30" name="send" type="submit"><span>send message</span></button>
            </div>
        </div>
   </fieldset>
</form>

<script type="text/x-magento-init">
    {
        "#customer-comments-form": {
            "validation": {},
            "phNoValidation":{}
        }
    }
</script>