<form class="form" id="find_coin_form" method="post" autocomplete="off" action="<?php echo $this->getUrl("webforms/index/post")?>">
   <fieldset class="fieldset">
       <legend class="legend"><span><?= $block->escapeHtmlAttr(__('FIND YOUR COIN')) ?></span></legend><br>
        <div class="field required">
            <label for="cust_fn" class="label"><span><?= $block->escapeHtmlAttr(__('First Name')) ?></span></label>
            <div class="control">
                <input type="text" name="cust_fn" id="cust_fn" value=""  class="input-text" data-validate="{required:true}" style="width:60%;">
            </div>
        </div>

        <div class="field required">
            <label for="cust_ln" class="label"><span><?= $block->escapeHtmlAttr(__('Last Name')) ?></span></label>
            <div class="control">
                <input type="text" name="cust_ln" id="cust_ln" value=""  class="input-text" data-validate="{required:true}" style="width:60%;">
            </div>
        </div>

       
        <div class="field required">
            <label for="cust_email" class="label"><span><?= $block->escapeHtmlAttr(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="cust_email" id="cust_email" value=""  class="input-text" data-validate="{required:true, 'validate-email':true}" style="width:60%;">
            </div>
        </div>

        <div class="field required">
            <label for="cust_phone" class="label"><span><?= $block->escapeHtmlAttr(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text" name="cust_phone" id="cust_phone" value="" class="input-text" data-validate="{required:true,'country':true}" style="width:60%;">
            </div>
        </div>
      
       
        <div class="field required">
            <label for="cust_find" class="label"><span><?= $block->escapeHtmlAttr(__('I am Looking For')) ?></span></label>
            <div class="control">
 		<textarea name="cust_find" id="cust_find" value=""  class="input-text" data-validate="{required:true}" style="width:60%"></textarea>
            </div>
        </div>

        <div class="field required">
            <div class="control">
                <input type="text" name="form_type" id="form_type" value="coin"  class="input-text" data-validate="{required:true}" style="width:60%; display:none; ">
            </div>
        </div>
       
       
   </fieldset>

   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Submit Details"><span>Submit</span></button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#find_coin_form": {
            "validation": {},
            "customMethod":{}
        }
    }
</script>
