            <div class="content-container">
                <div class="content-top">
                    <div class="container">
                        <div class="content-inner_blk">
                            <div class="img-blk">
								<a href="">
                                <img src="<?php echo $block->getViewFileUrl('images/coin.png'); ?>" alt="" class="">
								</a>
                            </div>
                            <div class="price-blk">
                                <div class="price">$79<span class="price-sub"><span class="up">95</span><span class="down">+s&h</span></div>
                                  
                                <a href="<?php echo $block->getUrl('checkout/cart/') ?>" class="btn-buy btn btn-link" title="" >Buy Now</a>
                            </div>
                            <div class="amc-blk">

                                <img src="<?php echo $block->getViewFileUrl('images/amc_tv.png'); ?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="content-bottom">
                    <div class="container">

                        <div class="content-inner_blk">

                            <div class="content-blk">
                                <h2>2018 The Walking Dead “All Out War” Silver Coin</h2>
                                <ul class="desc">
                                    <li>Commemorating Season 8 of AMC’s <br/> The Walking Dead - “All Out War”</li>
                                    <li>One troy ounce of .999 Fine Silver</li>
                                    <li>Cook Island two dollar legal tender</li>
                                    <li>Includes custom box and coin holder</li>
                                </ul>
                                <div class="img-blk">
<a href="">
                                    <img src="<?php echo $block->getViewFileUrl('images/coin.png'); ?>" alt="" />
</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        
    </body>


    


