<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

$customHeaderLink = $this->helper('SomethingDigital\BryantPark\Helper\CustomHeaderLinks');
$about = $customHeaderLink->getAboutLink();
$contact = $customHeaderLink->getContactLink();
?>
<?php /** @var $block \Magento\Customer\Block\Account\RegisterLink */ ?>
<?php if (!$block->getLayout()->isBlock('register.customer.link')): ?>
    <li>
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?> >
            <?= $block->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php endif; ?>

<?php if ($about): ?>
    <li class="about-link">
        <a href="<?php echo $about ?>"><?php echo __('About') ?></a>
    </li>
<?php endif; ?>
<?php if ($contact): ?>
    <li class="contact-link">
        <a href="<?php echo $contact ?>"><?php echo __('Contact') ?></a>
    </li>
<?php endif; ?>
