<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php echo $this->getLayout()->createBlock("Earthlite\Customer\Block\Html\Logo")->setTemplate("Earthlite_Customer::html/logo.phtml")->toHtml(); ?>

<div class="block block-customer-login">
        <a class="action close" href="<?= $block->getUrl('') ?>"><span><?= $block->escapeHtml(__('Close')) ?></span></a>

    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="form-heading"><span><?= $block->escapeHtml(__('Sign in to your Earthlite account')) ?></span></div>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('')) ?>">
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="secondary">
                        <div class="remember-me choice">
                            <input name="login[rememberme]" type="checkbox"  class="input-checkbox" id="rememberme" title="<?php echo __('Remember me on this computer') ?>" >
                            <label for="rememberme"><span><?= $block->escapeHtml(__('Remember me')) ?></span></label>
                        </div>
                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                    </div>
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Login')) ?></span></button>
                        <span><?= $block->escapeHtml(__("Don't have an account?")) ?> <a class="action link" href="<?= $block->getUrl('*/*/create'); ?>"><?= $block->escapeHtml(__('Sign Up')) ?></a></span> 
                    </div>
                </div>
            </fieldset>
        </form>
        <div class="terms-block">
            <span> 
                By logging in you are agreeing to our <a class="action link" href="#">Terms & Conditions </a> and <a class="action link" href="#">Privacy Policy</a>
            </span>
        </div>
    </div>
</div>

