<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

 if ($block->getCurrentDirection() == 'desc') {
     $directionParam = '&product_list_dir=desc';
 } else {
     $directionParam = '';
 }
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>

    <ul id="sorter" data-role="sorter" class="sorter-select">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <li><a href="<?= $block->getPagerUrl("product_list_order=" . $_key . $directionParam) ?>" 
            <?php if ($block->isOrderCurrent($_key)): ?> 
                class="active"
            <?php endif; ?> 
            >
            <?= $block->escapeHtml(__($_order)) ?>
            </a></li>   
        <?php endforeach; ?>
    </ul>

    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="product_list_dir=desc"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href=""
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Catalog/js/sorter":{}
    }
}
</script>
