<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <label class="sorter-close"><?= $block->escapeHtml(__('Close')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options d-md-inline-block">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <ul data-role="sorter" class="sorter-select d-md-none">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <li><a href="<?= $block->getPagerUrl("product_list_order=" . $_key) ?>" 
            <?php if ($block->isOrderCurrent($_key)): ?> 
                class="active"
            <?php endif; ?> 
            >
            <?= $block->escapeHtml(__($_order)) ?>
            </a></li>   
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Catalog/js/sorter":{}
    }
}
</script>
