<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Deliverydate
 */
?>
</section><section class="admin__page-section amasty-deliverydate">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Delivery Information') ?></span>
    </div>
    <?php foreach ($this->getFormElements() as $element): ?>
        <?php echo $element->toHtml(); ?>
    <?php endforeach; ?>
