<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <?php 
                $stockItem = $_product->getExtensionAttributes()->getStockItem();
            ?>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php if ($_product->getTypeId() === 'bundle'): ?>
    <div class="actions">
        <button type="submit"
                title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                class="action primary tocart"
                id="product-addtocart-button">
            <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
        </button>
    </div>
<?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require(["jquery"],function($){
        incrementQty = parseInt(<?php echo $stockItem->getData('enable_qty_increments') ? $stockItem->getData('qty_increments') : 0;?>);
        
        $('#qty').on("blur",function(e){ 
            var currentQty = ($(this).val() == 0 || $(this).val() == '') ? incrementQty : $(this).val();
            if(incrementQty > 0){
                var updateQty = parseInt(Math.ceil( currentQty / incrementQty) * incrementQty);
                updateQty = ( updateQty == 0) ? currentQty : updateQty;
                $('#qty').val(updateQty)
            }    
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
