<?php
    $viewModel = $block->getViewModel();
    $enableLayeredNavigation = $viewModel->getLayerNavigationConfig();
?>
<div class="block filter layeredNavigation" id="layered-filter-block">
    <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
    <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
        <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Filter') ?></strong>
    </div>
    <div class="block-content filter-content">
        <?php echo $block->getChildHtml('state') ?>

        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <div class="block-actions filter-actions ">
                <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
            </div>
        <?php endif; ?>
        <?php $wrapOptions = false; $activeKey = 0; $activeArray = []; ?>
        <?php foreach ($block->getFilters() as $key => $filter): ?>
            <?php if ($filter->getItemsCount()): ?>
                <?php $range = implode(' ', range(0, $filter->getItemsCount())); ?>
                <?php if (!$wrapOptions): ?>                    
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Filter Options') ?></strong>
                    <div class="filter-options" id="narrow-by-list" data-role="content" <?php if($enableLayeredNavigation){?> data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "<?php echo $range; ?>", "multipleCollapsible": true}}'<?php }?> >
                <?php  $wrapOptions = true; endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                    <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                </div>
                <?php
                    if($block->getRequest()->getParam($filter->getRequestVar())){
                        $activeArray[] = $activeKey;
                    }
                    $activeKey++;
                ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($wrapOptions && $enableLayeredNavigation): ?>
            </div>
            <script type="text/x-magento-init">
                {
                    "#narrow-by-list": {
                        "accordion": {
                            "openedState": "active",
                            "collapsible": true,                            
                            "multipleCollapsible": true
                        },
                        "Earthlite_LayerNavigation/js/layer": {}
                    }
                }
            </script>
            <div id="filter_overlay" class="filter_overlay" style="display: none;">
                <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="Loading...">
            </div>
        <?php endif; ?>        
    </div>
</div>

