<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>

<?php
    $blockObj = $block->getLayout()->createBlock('Earthlite\ProductAvailability\Block\Product\View\AbstractView');
    $_product = $block->getProduct();
    $productionItemExist = false;
    $productionItem = $_product->getCustomAttribute('production_item')->getValue();
    $productId = $_product->getId();
    $stockItemQty = $blockObj->getStockQty($productId);
    if ($_product->getTypeId() == 'configurable') {
        $childItems = $_product->getTypeInstance()
                ->getUsedProducts($_product,['production_item']);
        $qty = [];
        foreach ($childItems as $child) {
            if ($child->getProductionItem()) {
                $productionItemExist = true;
            }
            $qty[] = $blockObj->getStockQty($child->getId());
        }
        $stockItemQty = max($qty);
    }
?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <?php if ($productionItem || $productionItemExist) :?>
            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('In stock')) ?></span>
            </div>
        <?php else :?>
            <?php switch (true):
                case $stockItemQty >=10: ?>
                    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                    </div>
                <?php break; ?>
                <?php case ($stockItemQty < 10 and $stockItemQty > 0):?>
                    <div class="stock low-available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('<10 available')) ?></span>
                    </div>
                <?php break; ?>
                <?php case ($stockItemQty == 0):?>
                    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </div>
                <?php break; ?>
            <?php endswitch; ?>
        <?php endif; ?>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
