
<?php

/**
 * Only used in Magento < 2.1
 */

$productId = $block->getRequest()->getParam('id');
$storeId = $block->getRequest()->getParam('store');

if (!$storeId) {
    $pointOfSales = $block->getPosModel()->getCollection();
} else {
    $pointOfSales = $block->getPosModel()->getPlacesByStoreId($storeId);
}
$ids = [];
foreach ($pointOfSales as $pointOfSale) {
    $ids[] = $pointOfSale->getPlaceId();
}
$stock = $block->getStockModel()->getStockSettings($productId, null, $ids);
$fieldName = "inventory";
?>
<?php if ($productId && in_array($stock->getTypeId(), $block->getHelperData()->getProductTypes()) && $block->isAuthorized() && (($stock->getMultistockEnabled() && $storeId) || !$storeId)): ?>




    <fieldset class="fieldset form-inline">
        <legend class="legend"><span>Advanced Inventory</span></legend>
        <br>



        <input type="hidden" name="product[inventory][mage]" value="2.0.0"/>


        <?php if (!$storeId) : ?>
            <div class="field">
                <label class="label" for="inventory_manage_stock">
                    <b><?php echo __('Enable multi-stock') ?></b>
                </label>
                <div class="control">
                    <select id="multistock" name='<?php echo $fieldName; ?>[multistock]' class="select" onChange="InventoryManager.enableMultiStock('multistock')">
                        <option value="0" <?php if (!$stock->getMultistockEnabled()) echo 'selected="selected"'; ?>><?php echo __('No') ?></option>
                        <option value="1" <?php if ($stock->getMultistockEnabled()) echo 'selected="selected"'; ?>> <?php echo __('Yes') ?></option>
                    </select>
                </div>
            </div>
        <?php else: ?>
            <input id="multistock" name='<?php echo $fieldName; ?>[multistock]' type='hidden' value="<?php echo ($stock->getMultistockEnabled()) ? 1 : 0; ?>">

        <?php endif ?>
        <div id= 'advancedinventory_stocks'>
            <?php
            $i = 0;

            foreach ($pointOfSales as $pointOfSale):
                if ($pointOfSale->getManageInventory() == 2) {
                    continue;
                }

                $posWh = $fieldName . "[pos_wh][" . $pointOfSale->getPlaceId() . "]";

                if ($pointOfSale->getStatus() == 0) {
                    $visibility = __('Warehouse (hidden)');
                } else {
                    $visibility = __('Point of Sales (visible)');
                }
                ?>
                <div class="field">
                    <label class="label"  for="inventory_manage_local_stock">
                        <?php echo $pointOfSale->getName(); ?> 

                        <br>
                        <span style="font-size:10px;
                              ">[<?php echo $visibility; ?>, code : <?php echo $pointOfSale->getStoreCode(); ?>]</span>
                    </label>
                    <div class="control">
                        <?php
                        $getQuantity = "getQuantity" . $pointOfSale->getPlaceId();
                        $getUseConfigSettingForBackorders = "getUseConfigSettingForBackorders" . $pointOfSale->getPlaceId();
                        $getBackorderAllowed = "getBackorderAllowed" . $pointOfSale->getPlaceId();
                        $getManageStock = "getManageStock" . $pointOfSale->getPlaceId();
                        $getStockId = "getStockId" . $pointOfSale->getPlaceId();

                        $getDefaultStockManagement = "getDefaultStockManagement" . $pointOfSale->getPlaceId();
                        $getDefaultUseDefaultSettingForBackorder = "getDefaultUseDefaultSettingForBackorder" . $pointOfSale->getPlaceId();
                        $getDefaultAllowBackorder = "getDefaultAllowBackorder" . $pointOfSale->getPlaceId();
                        $getDefaultStockManagement = "getDefaultStockManagement" . $pointOfSale->getPlaceId();
                        ?>

                        <select   name="<?php echo $posWh ?>[manage_stock]" class="select"  onchange='InventoryManager.showDetails(this)' style="width:293px;">
                            <option value="1" <?php if ((($stock->$getManageStock() && $stock->$getStockId()) || (!$stock->$getStockId() && $stock->$getDefaultStockManagement()))) echo 'selected="selected"'; ?>><?php echo __("Stock management enabled") ?></option>
                            <option value="0" <?php if ((!$stock->$getManageStock() && $stock->$getStockId()) || (!$stock->$getStockId() && !$stock->$getDefaultStockManagement())) echo 'selected="selected"'; ?>><?php echo __("Stock management disabled") ?></option>
                        </select>

                        <div class="pointofsale"<?php if ((!$stock->$getManageStock() && $stock->$getStockId()) || (!$stock->$getStockId() && !$stock->$getDefaultStockManagement())) echo "style='display:none';"; ?>>
                            <input  

                                style="width:50px;text-align:center" 
                                type="text" 
                                class="keydown input-text required-entry validate-number" 
                                name='<?php echo $posWh ?>[qty]'
                                value="<?php echo $block->getHelperData()->qtyFormat($stock->$getQuantity(), $stock->getIsQtyDecimal()); ?>" 
                                onchange="InventoryManager.updateQty()"

                                />

                            <?php
                            $backorders_checked = null;
                            $backorders_value = null;
                            $backorders_disabled = null;
                            // valeur non initiliasée
                            $getStockId = "getStockId" . $pointOfSale->getPlaceId();
                            if (!$stock->$getStockId()) {
                                $backorders_checked = $stock->$getDefaultUseDefaultSettingForBackorder();
                                $backorders_value = $stock->$getDefaultAllowBackorder();
                                $backorders_disabled = $stock->$getDefaultUseDefaultSettingForBackorder() ? true : false;
                            } else {
                                $backorders_checked = $stock->$getUseConfigSettingForBackorders();
                                $backorders_value = $stock->$getBackorderAllowed();
                                $backorders_disabled = $stock->$getUseConfigSettingForBackorders() ? true : false;
                            }
                            ?>

                            <select    <?php echo ($backorders_disabled) ? 'disabled="disabled"' : null; ?> name='<?php echo $posWh ?>[backorder_allowed]'  style="width:240px;">
                                <option value="0" <?php echo ($backorders_value == 0) ? 'selected' : null; ?> ><?php echo __('No backorders') ?></option>
                                <option value="1" <?php echo ($backorders_value == 1) ? 'selected' : null; ?>><?php echo __('Allow Qty below 0') ?></option>
                                <option value="2" <?php echo ($backorders_value == 2) ? 'selected' : null; ?>><?php echo __('Allow Qty below 0 and Notify Customer') ?></option>
                            </select>
                            <input    onclick="this.previous().disabled = this.checked;"<?php echo ($backorders_checked) ? 'checked' : null; ?> name='<?php echo $posWh ?>[use_config_setting_for_backorders]' type="checkbox" style="margin-left:40px"/> 
                            <?php echo __('Use Config Settings') ?>
                        </div>
                    </div>
                </div>
                <?php
                $i++;
            endforeach;
            ?>
        </div>
        <script language="javascript">
            if (typeof InventoryManager == "undefined") {
                InventoryManager = {};
            }
            InventoryManager.autoUpdateStockStatus = <?php echo $block->getHelperCore()->getStoreConfig("advancedinventory/settings/auto_update_stock_status"); ?>;
        </script>


    </fieldset>


<?php endif;
