<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */

/** @var \PartySupplies\CompanyRegistration\ViewModel\Register $register */
$register = $block->getData('register_viewModel');
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= $block->escapeHtml(__('Lorem ipsum dolor sit amet, consectetur adipiscing elit')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Register User')) ?></span></a>
            </div>
            <p><?= $block->escapeHtml(__('or')) ?></p>
            <div class="primary">
                <a href="<?= $block->escapeUrl($register->getRegisterUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Register Company')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
