# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed.

"http://{default}/":
    type: upstream
    upstream: "mymagento:http"

"http://livingearthcraft.{default}/":
    type: upstream
    upstream: "mymagento:http"

"http://continuumpedicure.{default}/":
    type: upstream
    upstream: "mymagento:http"

"http://taraspatherapy.{default}/":
    type: upstream
    upstream: "mymagento:http"

"http://{all}/":
    type: upstream
    upstream: "mymagento:http"

"https://{all}/":
    type: upstream
    upstream: "mymagento:http"
