# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed.

"http://{default}/":
    type: upstream
    upstream: "mymagento:php"

"https://{default}/":
    type: upstream
    upstream: "mymagento:php"

"http://{all}/":
    type: upstream
    upstream: "mymagento:php"

"https://{all}/":
    type: upstream
    upstream: "mymagento:php"

