<?php
/**
 * Call for price popup
 *
 * @var $block \Ziffity\Header\Block\Header
 */
?>
<?php
    $storeInfo = $block->getConfigValue();
    $wHeader = $storeInfo['welcome_header'];
    $stTiming = $storeInfo['store_timings'];
    $stPhone = $storeInfo['store_phone'];
?>
<div class="hidden">
    <div class="clearfix" id="callforquote-popup">
        <div class="contact-content">
            <div class="contact-title"><?= __('Call For Price') ?></div>
            <div class="ph">
                <p><?= __('Phone Number:') ?> <?= $stPhone ?></p>
            </div>
            <div class="timing">
                <p><?= __('Business hours:') ?> <strong><?= $stTiming ?></strong></p>
            </div>
       </div>
    </div>
</div>
