<div class="pre-loader" style="background-image: url('<?php echo $block->getViewFileUrl('images/loader-3.gif') ?>')"></div>
<script>
    require(['jquery'], function($){
        $(window).load(function() {
            $(".pre-loader").fadeOut("slow");
	});
    });
</script>
<style>
.pre-loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: center no-repeat rgba(0, 0, 0, 0.6);
}
</style>
    