<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php
$_product = $block->getProduct();
?>
<div class="product-info-stock-sku">
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability:') ?>">
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability:') ?>">
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
</div>
<?= $block->getChildHtml('bundle_prices') ?>
