<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
$isCustomerLoggedIn = $block->getWishlistHelper()->isCustomerLogIn();
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <a href="javascript:void(0);"
       class="action towishlist <?= $isCustomerLoggedIn ? '' : 'wishlist-signin'?>"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       <?php if($isCustomerLoggedIn) : ?>
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       <?php else : ?>
       params='<?= $block->getAddToWishlistParams($block->getProduct()) ?>'
       <?php endif ?>
       data-action="add-to-wishlist"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif; ?>

