<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<?php 
if ($block->isLoggedIn()) {?>
    <li>
        <a  href="/sales/orders/history">
           <span><?= __('My Orders') ?></span>
        </a>
    </li>
    <li>
        <a  href="/wishlist">
           <span><?= __('My Wishlist') ?></span>
        </a>
    </li>
    <li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
            <?= $block->escapeHtml($block->getLabel()) ?>
        </a>
    </li>
<?php  }?>
<?php 
if (!$block->isLoggedIn()) { ?>
    <li class="signin-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> >  
            <i class="fa fa-user"></i>
            <span><?= __('My Account') ?></span>
        </a>
    </li>
<?php }?>