<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                       value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                    <div class="field choice addons-section">
                        <input id="addons-bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>" type="checkbox" value="<?= /* @escapeNotVerified */ $_option->getId() ?>"/>
                        <label class="label"
                               for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>">
                            <span><?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    requirejs(['jquery'], function($) {
        $(function() {
            $("div.addons-section").on("click",function(event) {
                var target = $(event.target);
                if (target.is('input:checkbox')) return;

                var checkbox = $(this).find("input[type='checkbox']");

                if(checkbox.prop("checked")){
                    debugger;
                    //console.log(checkbox.attr('id').replace("addons-", ""));
                    checkbox.prop("checked",false);
                    var id = checkbox.attr('id').replace("addons-", "");
                    $(id).attr('checked', false);
                    //$('#'+id).clone().appendTo("#product_addtocart_form");
                } else if(!checkbox.prop("checked")) {
                    debugger;
                    checkbox.prop("checked",true);
                    var id = checkbox.attr('id').replace("addons-", "");
                    $(id).attr('checked', true);
                }
            });
        });
    });
</script>