<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list row">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                       value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                <?php
                $imageHelper = $this->helper('\Magento\Catalog\Helper\Image');
                $image_url = $imageHelper->init($_selection, 'product_page_image_small')->setImageFile($_selection->getFile())->resize(200, 200)->getUrl();
                ?>
                    <div class="product-item col-12 col-md-4 col-lg-3">

                        <div class="product-item-info">
                            <div class="field choice addons-section">
                                <input id="addons-bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>" type="checkbox" value="<?= /* @escapeNotVerified */ $_option->getId() ?>"/>
                                <label class="label"
                                       for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>">
                                    <span class="label-text"><?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                                </label>
                            </div>
                            <div class="product-item-photo">
                                <img src="<?= $image_url ?>">
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection) ?>
                                </strong>
                            </div>
                        </div>

                    </div>
                <?php endforeach; ?>
                <!--<div id="bundle-option-<?php /* @escapeNotVerified */ //$_option->getId() ?>-container"></div> -->
                <!-- commented for no use -->
            <?php endif; ?>
        </div>
    </div>
</div>
<script>
    requirejs(['jquery', 'slick'], function($) {
        $(function() {
            $("div.addons-section").on("click",function(event) {
                var target = $(event.target);
                if (target.is('input:checkbox')) return;

                var checkbox = $(this).find("input[type='checkbox']");

                if(checkbox.prop("checked")){
                    checkbox.prop("checked",false);
                    var id = checkbox.attr('id').replace("addons-", "");
                    $(id).attr('checked', false);
                } else if(!checkbox.prop("checked")) {
                    checkbox.prop("checked",true);
                    var id = checkbox.attr('id').replace("addons-", "");
                    $(id).attr('checked', true);
                }
            });
            $('.product-info-wrap').siblings('.product-options-wrapper').find('.options-list').slick({
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 3,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            slidesToShow: 1
                        }
                    }
                ]
            }).on('setPosition', function (event, slick) {
                slick.$slides.css('height', slick.$slideTrack.height() + 'px');
            });
        });
    });
</script>