<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$customHeaderLink = $this->helper('SomethingDigital\BryantPark\Helper\CustomHeaderLinks');
$about = $customHeaderLink->getAboutLink();
$contact = $customHeaderLink->getContactLink();
?>
<?php /** @var $block Magento\Framework\View\Element\Html\Link */ ?>
<?php if($block->getChildHtml()):?>
<li class="customer-register links-container">
    <span class="links-container-title"
          role="link"
          tabindex="0"
          data-mage-init='{"dropdown":{}}'
          data-toggle="dropdown"
          data-trigger-keypress-button="true">
        <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
        <button type="button"
                class="action switch"
                tabindex="-1">
            <span><?= $block->escapeHtml(__('Change')) ?></span>
        </button>
    </span>
    <div class="customer-menu" data-target="dropdown">
        <ul class="header links">
            <?= $block->getChildHtml() ?>
        </ul>
    </div>
</li>
<?php endif; ?>

<?php if ($about): ?>
    <li class="about-link">
        <a href="<?php echo $about ?>"><?php echo __('About') ?></a>
    </li>
<?php endif; ?>
<?php if ($contact): ?>
    <li class="contact-link">
        <a href="<?php echo $contact ?>"><?php echo __('Contact') ?></a>
    </li>
<?php endif; ?>

