<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */

/** @var \PartySupplies\CompanyRegistration\ViewModel\Register $register */
$register = $block->getData('register_viewModel');
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>

<div class="inner-wrapper">
    <div class="benefits-wrapper">
        <h2 class="heading"><?= $block->escapeHtml(__('Business Accounts Benefits')) ?></h2>
        <div class="benifits-list-wrap">
            <div class="benifits-list">
                <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('business_account_benefits')->toHtml(); ?>
                <h3 class="download-title"><?= $block->escapeHtml(__('Business Accounts Benefits')) ?></h3>
            </div>
            <a class="btn btn-black" href="pub/media/reseller-certificate/form.pdf" download="">Download</a>
        </div>
    </div>

    <div class="form-wrapper">
        <form class="form create account form-create-account" action="<?= $block->escapeUrl($register->getRegisterPostUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}'>
            <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
            <div class="fieldset create info">
                <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
                <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
                <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company'); ?>
                <?php if ($_company->isEnabled()) : ?>
                    <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                <?php endif ?>
            </div>

            <div class="fieldset address">
                <input type="hidden" name="create_address" value="1" />


                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                <div class="field street required">
                    <label for="street_1" class="label"><span><?= /* @noEscape */ $block->escapeHtml(__('street1')) ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    </div>
                </div>

                <div class="field street">
                    <label for="street_2" class="label"><span><?= /* @noEscape */ $block->escapeHtml(__('street2')) ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(1)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_2" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    </div>
                </div>

                <div class="field required">
                    <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                    <div class="control">
                        <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>" id="city">
                    </div>
                </div>

                <div class="field region required">
                    <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                    <div class="control">
                        <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                            <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                        </select>
                        <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>" style="display:none;">
                    </div>
                </div>

                <div class="field country required">
                    <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                    <div class="control">
                        <?= $block->getCountryHtmlSelect() ?>
                    </div>
                </div>

                <div class="field zip required">
                    <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                    <div class="control">
                        <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                    </div>
                </div>

                <div class="field required">
                    <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>

                <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
                <?php if ($_telephone->isEnabled()) : ?>
                    <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                <?php endif ?>

                <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                <div class="field field-file required">
                    <label for="reseller_certificate" class="label"><span><?= $block->escapeHtml(__('resellerCertificate')) ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" readonly data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true}">


      <input type="file" name="reseller_certificate" id="reseller_certificate" value="<?= $block->escapeHtmlAttr($block->getFormData()->getResellerCertificate()) ?>" title="<?= $block->escapeHtmlAttr(__('resellerCertificate')) ?>" class="input-file upload up">
                        <span class="file-custom">
      <span class="btn" id="upload"><?= $block->escapeHtml(__('Upload')) ?></span>
    </span>
                    </div>
                </div>

                <?= $block->getChildHtml('form_additional_info') ?>

                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                <?php if ($addressAttributes) : ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                    <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                <?php endif; ?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">


                <div class="actions-toolbar field">
                    <div class="primary">
                        <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></button>
                    </div>
                </div>

            </div>

            <div class="actions-toolbar">
                <div class="secondary">
                    <span><?= $block->escapeHtmlAttr(__("Already have an account?")) ?></span>
                    <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Sign In')) ?></span></a>
                </div>
            </div>
        </form>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
<script>
    var uploadField = document.getElementById("reseller_certificate");
    <?php $allowedFileSize = $register->getScopeConfigValue('reseller_certification/general/max_filesize_limit'); ?>
    uploadField.onchange = function() {
        if (this.files[0].size > <?= $register->convertMBtoBytes($allowedFileSize) ?>) {
            alert("<?= $block->escapeHtml(__("uploadFileTooLarge", $allowedFileSize)) ?>");
            this.value = "";
        };
    };
</script>