<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block SomethingDigital\OrderHistory\Block\Sales\OrderDetails*/?>
<div class="order-details-items ordered">
    <?php $orderData = $block->getOrder() ?>
    <?php $order = $orderData->getData()[0];?>
    <?php $discountAmnt = $block->getDiscount($order['LineItems']); ?>

    <div class="order-title">
        <strong><?= /* @escapeNotVerified */ __('Items Ordered') ?></strong>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items" id="my-orders-table" summary="<?= /* @escapeNotVerified */ __('Items Ordered') ?>">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items Ordered') ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                    <th class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                    <th class="col price"><?= /* @escapeNotVerified */ __('Price') ?></th>
                    <th class="col qty"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                    <th class="col subtotal"><?= /* @escapeNotVerified */ __('Subtotal') ?></th>
                </tr>
            </thead>
            <?php $items = $order['LineItems']; ?>
            <tbody>
                <?php foreach ($items as $item): ?>
                    <?php
                        $productUrl = $block->getProductUrl($item['SKU']);
                    ?>
                    <tr id="order-item-row-<?= $item['SKU'] ?>">
                       <td class="col name" data-th="<?= __('Item') ?>">
                          <strong class="product name product-item-name"><a href="<?= $productUrl ?>"><?= $block->escapeHtml($item['Title']) ?></a></strong>
                       </td>
                       <td class="col sku" data-th="<?= __('SKU') ?>"><a href="<?= $productUrl ?>"><?= $block->escapeHtml($item['SKU']) ?></a></td>
                       <td class="col price" data-th="<?= __('Price') ?>">
                            <span class="price-excluding-tax" data-label="<?= __('Excl. Tax') ?>">
                                <span class="cart-price">
                                    <span class="price"><?= $block->getCurrencyFormat($block->escapeHtml($item['SoldPrice'])) ?></span> 
                                </span>
                            </span>
                       </td>
                       <td class="col qty" data-th="<?= __('Qty') ?>">
                          <ul class="items-qty">
                             <li class="item">
                                <span class="title"><?= __('Ordered') ?></span>
                                <span class="content"><?= $block->escapeHtml($item['Qty']) ?></span>
                             </li>
                          </ul>
                       </td>
                       <td class="col subtotal" data-th="<?= __('Subtotal') ?>">
                          <span class="price-excluding-tax" data-label="<?= __('Excl. Tax') ?>">
                              <span class="cart-price">
                                  <span class="price"><?= $block->getCurrencyFormat($block->escapeHtml(($item['SoldPrice']*$item['Qty']))) ?></span>
                              </span>
                          </span>
                       </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr class="subtotal">
                    <th colspan="4" class="mark" scope="row">
                        <?= __('Subtotal') ?>
                    </th>
                    <td class="amount" data-th="<?= __('Subtotal') ?>">
                    <span class="price"><?= $block->getCurrencyFormat($order['TotalLineOrdered']) ?></span>
                    </td>
                </tr>
                <?php if ($discountAmnt != 0): ?>
                    <tr class="discount_amount">
                        <th colspan="4" class="mark" scope="row">
                          <?= __('Discount') ?>
                        </th>
                        <td class="amount" data-th="<?= __('Subtotal') ?>">
                        <span class="price"><?= $block->getCurrencyFormat($discountAmnt) ?></span>
                        </td>
                    </tr>
                <?php endif; ?>
                <tr class="shipping">
                    <th colspan="4" class="mark" scope="row">
                        <?= __('Shipping &amp; Handling') ?>
                    </th>
                    <td class="amount" data-th="<?= __('Shipping &amp; Handling') ?>">
                        <span class="price"><?= $block->getCurrencyFormat($order['ShippingCharge']) ?></span>
                    </td>
                </tr>
                <tr class="tax">
                    <th colspan="4" class="mark" scope="row">
                        <?= __('Tax') ?>
                    </th>
                    <td class="amount" data-th="<?= __('Tax') ?>">
                        <span class="price"><?= $block->getCurrencyFormat($order['TaxTotal']) ?></span>
                    </td>
                </tr>
                <tr class="grand_total">
                    <th colspan="4" class="mark" scope="row">
                        <strong><?= __('Grand Total') ?></strong>
                    </th>
                    <td class="amount" data-th="<?= __('Grand Total') ?>">
                        <strong><span class="price"><?= $block->getCurrencyFormat($order['TotalInvoiceAmount']) ?></span></strong>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= /* @escapeNotVerified */ $block->getBackUrl() ?>">
                <span><?= /* @escapeNotVerified */ $block->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
