<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var SomethingDigital\OrderHistory\Block\Sales\History $block */

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<div class="table-wrapper orders-history">
    <h3 class="orders-history-header"><?= __('Search By') ?></h3>
    <form action="<?php echo $block->getRequest()->getUriString(); ?>">
        <div class="order-search">
            <div>
                <label for="order-number"><?= __('Order Number') ?></label>
                <input value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getRequest()->getParam('sxOrderNumber')) ?>" type="text" id="order-number" name="sxOrderNumber" />
            </div>
            <div>
                <label for="customer-po-number"><?= __('PO Number') ?></label>
                <input value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getRequest()->getParam('poNumber')) ?>" type="text" id="customer-po-number" name="poNumber" />
            </div>
            <div>
                <label for="item-number"><?= __('Item Number') ?></label>
                <input value="<?= /* @escapeNotVerified */ $block->escapeHtml($block->getRequest()->getParam('productSku')) ?>" type="text" id="item-number" name="productSku" />
            </div>
            <button type="submit"><?= __('Search') ?></button>
        </div>
    </form>
    <?php if ($_orders && count($_orders)): ?>
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $block->escapeHtml($_order->getData('SxId')) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->escapeHtml($_order->getData('Date')) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= /* @escapeNotVerified */ $block->escapeHtml($_order->getData('ShipTo')['ToName']) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $block->escapeHtml($_order->getData('Total')) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        	<a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
    <?php endif ?>
</div>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>