<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image lazyload ls-animate"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
