<div id="page-preloader">

   <div class="tm-thecube">

      </div>

</div>

<script type="text/javascript">
   window.onload = function() {
       function fadeOut(el){
           el.style.opacity = 1;
           var last;
           var tick = function() {
               el.style.opacity = +el.style.opacity - (new Date() - last) / 600;
               last = +new Date();
               if (+el.style.opacity > 0) {
                   (window.requestAnimationFrame && requestAnimationFrame(tick)) || setTimeout(tick, 100);
               } else{
                   el.style.display = "none";
               }
           };
           tick();
       }
       var pagePreloaderId = document.getElementById("page-preloader");
       setTimeout(
           function () {
               fadeOut(pagePreloaderId)
           }, 1000);
   };
</script>