<div id="sticky-social" class="sticky-container">
    <ul class="sticky">
        <li class="facebook"><a href="http://www.facebook.com/CableShoppingNetwork" onclick="ga('send','event','SocialMediaFacebook', 'click','FacebookCsn')" target="_blank"><i class="fa fa-facebook"></i></a></li>
        <li class="twitter"><a href="https://twitter.com/shopcsntvcoins" onclick="ga('send','event','SocialMediaTwitter', 'click','TwitterCsn')" target="_blank"><i class="fa fa-twitter"></i></a></li>
        <li class="linkedin"><a href="https://www.linkedin.com/company/cable-shopping-network" onclick="ga('send','event','SocialMediaLinkedIn', 'click','LinkedInCsn')" target="_blank"><i class="fa fa-linkedin"></i></a></li>
    </ul>
    <span class="trigger fa fa-chevron-circle-left"></span>
</div>