<?php
//@codingStandardsIgnoreFile
/** @var $block \Mirasvit\FraudCheck\Block\Adminhtml\Score\Preview */
$orders = $block->getOrders();
?>
<div style="margin-top: 2rem">
    <?php foreach ($orders as $order): ?>
        <div style="background: #f8f8f8; margin-bottom: 0.2rem; padding: .5rem 1rem;">
            <div>
                Order: #<?= $order->getIncrementId() ?>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="<?= $block->getUrl('sales/order/view', ['order_id' => $order->getId()]) ?>" target="_blank">view</a>
            </div>
            <div>
                <?= __('Fraud Score:') ?> <?= $block->getFraudScore($order) ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
<style>
    body {
        color: #41362f;
        font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
        font-style: normal;
        font-weight: 400;
        line-height: 1.36;
        font-size: 14px;
    }

    a {
        color: #007bdb;
        text-decoration: none;
    }
</style>