<?php /** @var $block \Magento\Catalog\Block\Product\Image */
$_helper = $this->helper('Magebees\Lazyload\Helper\Data');
$config=$_helper->getConfig();
if(isset($config['loadingicon'])) {
    $image=$config['loadingicon'];
    $image_url=$_helper->getImageUrl($image);
} else {
    $image_url=$block->getViewFileUrl('Magebees_Lazyload::images/loader.gif');
}

$actionName = $this->getRequest()->getFullActionName();
if($actionName == 'wishlist_index_send'){
    $image_url = $block->getImageUrl();
}
?>
<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
		<img class="product-image-photo magebees_lazyload"
            <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
             src="<?= /* @escapeNotVerified */ $image_url ?>"			 
             data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
             width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth() ?>"
             height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight() ?>"
             alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>

