<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Framework\View\Element\Template $block */
?>
<!--
<form action="" method="post" id="form-validate" class="form send confirmation" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <p class="field note"><?= $block->escapeHtml(__('Please enter your email below and we will send you the confirmation link.')) ?></p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action send primary"><span><?= $block->escapeHtml(__('Send confirmation link')) ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>" class="action back"><span><?= $block->escapeHtml(__('Back to Sign In')) ?></span></a>
        </div>
    </div>
</form>
-->
<div class="log-in"  id="confirm-popup" style="display:none">
    <div class="sign-in-page">
        <div><h1>Welcome back!</h1></div>
        <div><p>America's Trusted Source of Numismatic Treasures</p></div>
    </div>
    <div class="block block-customer-login">
        <div class="common-form sign-in">
            
            <div class="block-title main-head text-center">
                <h3>
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Welcome Back!')) ?></strong>
                </h3>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
               <form action="" method="post" id="form-validate" class="form form-login wpcf7-form form send confirmation" data-mage-init='{"validation":{}}'>
                    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <p class="field note"><?= $block->escapeHtml(__('Please enter your email below and we will send you the confirmation link.')) ?></p>
                        <div class="field email required">
                            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input type="email" name="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                    </fieldset>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action send primary"><span><?= $block->escapeHtml(__('Send confirmation link')) ?></span></button>
                        </div>
                        <div class="secondary">
                            <a href="<?= $block->escapeUrl($block->getLoginUrl()) ?>" class="action back"><span><?= $block->escapeHtml(__('Back to Sign In')) ?></span></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="social">
            <div class="text-center mb-20">
                <h4>Or Connect Using</h4>
            </div>
            <div class="social-media">
                <ul class="list-inline">
                    <li class="social-links media-first">
                        <a href="#" class="button-social">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_fb.png'); ?>" alt="fb-icon" class="social-icon" />
                            <span class="button-social social-text"><?= __('Facebook') ?></span>
                        </a>
                    </li>
                    <li class=" social-links media-second">
                        <a href="#" class="button-social ">
                            <img src="<?php echo $this->getViewFileUrl('images/icon_google.png'); ?>" alt="google" class="social-icon" />
                            <span class="button-social social-text"><?= __('Google') ?></span>
                        </a>
                   </li>
               </ul>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
require(['jquery','Magento_Ui/js/modal/modal'],
function($, modal) {
    var options = {
           type: 'popup',
           responsive: true,
           innerScroll: true,
           modalClass: 'confirm-popup',
           buttons: false,
       };
    
        var popup = modal(options, $('#confirm-popup'));
        //$('#popup-modal-signup').modal('closeModal');
        $('#confirm-popup').modal('openModal');
    
});
</script>
