<!-- Category hit template -->
<script type="text/template" id="autocomplete_categories_template">
    <a class="algoliasearch-autocomplete-hit" href="{{url}}">
        <div>
            <div>
                {{#_highlightResult.name}}
                {{{_highlightResult.name.value}}}
                {{/_highlightResult.name}}
                {{^_highlightResult.name}}
                {{{name}}}
                {{/_highlightResult.name}}

                {{#product_count}}
                <small>({{product_count}})</small>
                {{/product_count}}
            </div>
        </div>
    </a>
</script>
