<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<script type="text/template" id="menu-template">
    <div class="autocomplete-wrapper">
        <div class="col9">
            <div class="aa-dataset-products"></div>
        </div>
        <div class="col3">
            <div class="other-sections">
                <div class="aa-dataset-suggestions"></div>
                <?php for ($i = 0; $i < 10; $i++) : ?>
                    <div class="aa-dataset-<?php echo $block->escapeHtml($i); ?>"></div>
                <?php endfor; ?>
            </div>
        </div>
    </div>
</script>
