<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php 
$_product = $block->getProduct();
$inventory = $block->getLayout()->createBlock('\Ziffity\Inventory\Block\SourceStock')->getSourceInventory($_product->getSku(), $_product->getId(), $_product->getTypeId());
?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable() && $inventory): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
