<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>

<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>" <?php echo ($_option->getRequired()) ? '': 'id="div-addons"'; ?> >
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
                <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                    <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selections[0])->toHtml(); ?>
                <?php endif; ?>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                    <div class="bundle-item">
                        <div class="field choice">
                            <input class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> checkbox product bundle option change-container-classname"
                                   id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                   type="checkbox"
                                   <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                   data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                   <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                                   <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                                   value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                        </div>
                    </div>
                    <?php if ($selectionBlock = $block->getChildBlock('product.info.bundle.option.checkbox.selection')): ?>
                        <?php /* @escapeNotVerified */ echo $selectionBlock->setOption($_option)->setSelection($_selection)->toHtml(); ?>
                    <?php endif; ?>
                <?php endforeach; ?>
<!--                <div id="bundle-option-<?php /* @escapeNotVerified */ //echo $_option->getId() ?>-container"></div>-->
            <?php endif; ?>
        </div>
    </div>
<?php if($_option->getRequired()) :?>
    <?php
        $product = $block->getProduct();
        $colors = $product->getCustomProductColor();
        $opt_arr = json_decode($colors);
        $heights = $product->getCustomProductHeight();
        $height_options = json_decode($heights);
    ?>
    <?php if(!empty($opt_arr)) : ?>
        <label class="label">
            <span><?= __('Color') ?></span>
        </label>
        <div class="custom-bundle-option">
            <select class="option">
                <?php foreach($opt_arr as $opt): ?>
                    <option value="<?= $block->getProducturl($opt->sku); ?>"><?= $opt->color; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    <?php endif; ?>

    <?php if(!empty($height_options)) : ?>
        <label class="label">
            <span><?= __('Height') ?></span>
        </label>
        <div class="custom-bundle-option">
            <select class="option">
                <?php foreach($height_options as $option): ?>
                    <option value="<?= $block->getProducturl($option->sku); ?>"><?= $option->height; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    <?php endif; ?>
<?php endif; ?>
</div>
<script>
    require(['jquery'], function($){
        $('select.option').on('change', function() {
            window.location.href =  this.value ;
        }); 
    });
</script>
