<?php
/**
 * Copyright © 2015 ziffitycommerce. All rights reserved.
 */
?>
<form id="custom-form" action="<?php echo $block->getFormAction() ?>" method="post">
    <fieldset class="fieldset">
        <legend class="legend" ><span><?php echo $block->hello; ?></span></legend>
</span></label>
    <div class="name">
        <label class="name"><span><?php echo __("Name") ?></span></label>
   <input type="text" name="name" calss="input-text" data-validate="{required:true}" />
    </div>
    <label class="email"><span><?php echo __("Email") ?></span></label>
   <div class="email">
   <input type="email" name="email" class="input-text" data-validate="{required:true, 'validate-email':true}"/>
   </div>
    <label class="description" ><span><?php echo __("Description") ?></span></label>
    <div class="description">
    <textarea name="description" data-validate="{required:true}" size="2"></textarea>
    </div>
    <div class="actions">
    <button type="submit" title="<?php echo __('Submit') ?>"><span><?php echo __('Submit') ?></span></button>
    </div>
    </fieldset>
</form>




<script type="text/x-magento-init">
    {
        "#custom-form": {
            "validation": {}
        }
    }
</script>